### ISSUE TITLE
Add feature to allow individual teams concurrent logins/sessions

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#122]
**Is your feature request related to a problem?** 

No.  This is a new feature.

**Feature Description**:

Currently pc2 only allows one login per client/team.  If a second
login is successful the previous session is disconnected (logged off)

For example, team 5 can only have one connection/login/session at a time.

The new feature is to allow any team (ex team 5) to login more than one time. 
If team 5 has 3 team members, this will allow all 3 team members to have
their own session/login.

**Have you considered other ways to accomplish the same thing?** 

Yes.  This change requires new/updated code.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** If so, please describe.  

At this time prototyping/analysis is being done.

**Additional context**: 

None.

**Comment by clevengr** [comment]
In an email regarding a separate feature request (Issue #125), Lee Wittenberg commented as follows:

```
 I'd also like some way to suppress all the pop-up
windows whenever a team logs into PC^2 when already logged in.  We get
far too many of these, and they're always distracting.
```

This seems related to the current issue ("Add feature to allow individual teams concurrent logins"):  when the Admin is given the ability to allow multiple logins, it seems like it would also be useful and relevant to add a second Admin feature:  "Enable/disable security notifications for duplicate logins".   These of course are going to need to be disabled if multiple logins are allowed; giving the Admin the option of disabling them when multiple logins are NOT allowed seems like a good user-friendly feature (as Lee suggests).
