### ISSUE TITLE
CreateVersionAndJar.xml uses Java 7, causing errors.

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#139]
**Describe the issue**: 
The script `createVersionAndJar.xml` has four places where it specifies Java 1.7 as the Java version:
```xml
    <property name="apt.build.javac.target" value="1.7" />
    <property name="apt.build.javac.source" value="1.7" />
    ...
    <property name="javacSource" value="1.7" />
    <property name="javacTarget" value="1.7" />
```
The latest develop branch (11/24/20) contains code that uses Java 8.  This causes `createVersionAndJar.xml` to generate compiler errors.

**To Reproduce**: 
Download the latest (11/24/20) version of the code, then run `createVersionAndJar.xml` as an Ant build.

**Expected behavior**: 
Should create new **Version** and **pc2.jar** files.

**Actual behavior**: 
Generates compiler errors, build fails.

**Environment**:
Windows 10, Java 8_201.

**Suggested Fix**:
Replace the four statements in `createVersionAndJar.xml` which specify `value=1.7` with `value=18.`.  This has been tested already and it solves the problem.

**Comment by troy2914** [comment]
btw, i notice projects/EWTeam/build.xml is using 1.6
