### ISSUE TITLE
Race condition in runProgram

### ISSUE THREAD

**Issue by troy2914** [pc2ccs/pc2v9#161]
This was actually discovered by Keith,
"During my testing on my ubuntu 16.04 linux machine(old I know), I often encounter the case where execute runs the program, but fails to capture the output properly."  This was observed by running `date +%s` repeatedly,  about half the time the output was not captured.

**Comment by lane55** [comment]
An educated guess as to why this bug was not discovered in pc2 is that when pc2 executes programs they
tend to take more CPU cycles so this timing bug was not encountered.

**Comment by troy2914** [comment]
Executable was handling this properly.   This ProgramRunner is only used by InputValidatorRunner.
