### ISSUE TITLE
Setting of "Allow Multiple Team Logins" is not preserved properly

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#206]
**Describe the issue**: 
  At the 2020 PacNW Contest (in March 2021) we noticed that if changes were made on the Admin "Settings" tab after the "Allow Multiple Logins Per Team" checkbox had already been checked and saved ("Update" pressed), the value of the "Allow Multiple Logins" checkbox returned to "unchecked".

  Further testing seems to indicate the following:
- the checkbox state is properly saved on the server when it is initially checked and followed by an "Update" (that is, if you check the box, click "Update", then exit and restart the Admin, the box does come back "checked", as it should).
- When you FIRST make a change to some other settings, whether it is changing ONE setting or MULTIPLE settings, pressing UPDATE incorrectly causes the "Allow Multiple Logins" checkbox to get cleared.
- If you make SUBSEQUENT changes to other settings (whether a single change or multiple changes), pressing UPDATE does NOT alter the state of the "Allow Multiple Logins" checkbox.

**To Reproduce**: 
- Start an Admin
- On the Settings tab, check "Allow Multiple Logins per Team"
- Click Update.
- Exit the Admin
- Restart the Admin, select the Settings tab, verify that "Allow multiple logins per team" is checked (it should be).
- Change any other setting on the Settings tab
- Click "Update".

**Expected behavior**:   
The new setting you changed should be reflected on the Settings screen, but the "Allow multiple logins per team" checkbox should NOT have changed (it should still be CHECKED).

**Actual behavior**: 
Pressing UPDATE after changing some other setting causes the "Allow multiple logins per team" checkbox to become UNCHECKED.  Shutting down the Admin and restarting it also causes the checkbox to come up UNCHECKED -- meaning, the "checked" state has been permanently lost.

**Environment**: 
 - Windows 8.1 with Java 1.8.0_201 (but it probably happens under any environment)
 - PC2 Version 9.7.0-6181

**Comment by lane55** [comment]
This is a duplicate issue of Issue #196 - marking #196 as a duplicate and assigning to clevengr to confirm
