### ISSUE TITLE
duplicate accounts

### ISSUE THREAD

**Issue by XuPuPG** [pc2ccs/pc2v9#229]
what is the motivation for allowing accounts with the same username and password to exist?

**Comment by clevengr** [comment]
Accounts are specific to a given contest SITE (an "account" is actually a combination of a site number and a team number).  In a multi-site contest, each site may want to number their teams (for example) starting at 1;  this feature allows such numbering if desired.

If this doesn't answer your question, you'll have to explain more about why you think it's possible to have different accounts with the same username...
