### ISSUE TITLE
Provide support for a "Read-only" Shadow.

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#240]
**Feature Description**: 
Currently it is only possible to run a single "Shadow" -- because the Shadow accepts submissions from the Remote CCS and _submits them to the PC2 Server_.  If there was more than one Shadow running, it would cause duplicated submissions to PC2.

This is not a problem if there's only one person monitoring the Shadow, or if all persons are in the same room and can look at the same screen.  However, in the age of 'virtual contests' this is not practical.  What's needed is a way to run a second (or third, or fourth) Shadow in "Read-only mode" -- that is, where the Read-only Shadow accepts remote submissions and displays shadow comparison results, _but does not submit the remote submissions to PC2_.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 
- Add a boolean flag "readOnlyMode" to the `RemoteEventFeedMonitor` class (which is what listens to the remote event feed and forwards submissions from that feed to the PC2 server).   
- In the main `while` loop in `RemoteEventFeedMonitor`, when it finds an event of type `submissions`, add a check for `readOnlyMode`.  If in readOnlyMode, _skip the code which sends the submission to PC2_.  Code to do this looks like:
```java
                                if ("submissions".equals(eventType)) {
                                    
                                    if (readOnly) {
                                        log.info("Skipping submission while in read-only mode");
                                        event = reader.readLine();
                                        continue;
                                    }
                            ... //process submission normally
```
This code was tested in the NADC21 Practice Contest and worked fine.

**More Implementation Details**: 

Add a pc2 Permission "Read-only Shadow" to the list of Account permissions.
By default Feeder 1 would be set to un-checked
All other accounts would be set to checked
This provides a way for any module to add a Shadow Mode Tab and not be able to Start Shadowing

Consider add log entries to log when:
Start Shadowing
stop Shadowing

**Additional context**: 
The value of `readOnlyMode` should be dynamically configurable at runtime.  For example, there should be a checkbox on the ShadowController GUI that enables/disables readOnlyMode on a per-client basis.

When a ShadowController is actually started and it is NOT in readOnlyMode, ideally it should check to see if there are any other Shadow clients running which are also not in readOnlyMode, and refuse to start a non-readonly shadow client if another already exists.

**Comment by clevengr** [comment]
To clarify:  the current situation (from code merged on 8 Aug 21) is that "Feeder1" can submit runs from the Event Feed to PC2, whereas any other Feeder account can LOOK AT the same Event Feed but _will not be able to submit runs from the Event Feed to PC2_.  Thus, the current implementation of "provide support for a Read-Only Shadow" is:  use any Feeder account _other than Feeder1_ to become a read-only Shadow.
This issue remains open because the recommended (intended) solution to the issue is to use Permissions to enforce the "read-only" restriction.

**Comment by lane55** [comment]
Closing - already merged
