### ISSUE TITLE
Add support for  entry_point

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#248]
**Feature Description**: 

Add support for CLICS CCS event feed entry_point.

Use entry_point when determining whether a program has compiled (aka exeName)
and to execute the teams submission.

Note that the Run class already has a field:
    private char[] entryPoint;

**Have you considered other ways to accomplish the same thing?** 

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 

**Additional context**:

**Comment by clevengr** [comment]
Is this a duplicate of Issue #46?    If not, how is this Issue different?

**Comment by lane55** [comment]
duplicate of #46 closing issue
