### ISSUE TITLE
Run status stays BEING_JUDGED

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#257]
**Describe the issue**: 

During a recent contest (using AWS machine), both the
Admin and Shadow tab showed the run status BEING_JUDGED
after runs were judged.

When admin and feeder were stopped and started the run status
showed judgements (aka not BEING_JUDGED), although newly submitted
runs did show BEING_JUDGED.

  The bug is that the client is not receiving the UPDATE_JUDGEMENT packet,
  here is proof:

  1 - that is the packet aka judgement that updates the Run grid

  2 - What seemed like a bug in edit run was not.   The grid
     showed BEING_JUDGED but edit run showed the run Judged
     because the admin got a copy of the Run from the server.

  3 - we both saw that the packet viewer listing did not
     contain an UPDATED_JUDGEMENT incoming packet.

  4 - the server's data is up to date (proven when we restarted
     the admin/feeder and the judgements showed up properly).

  So the bug is somewhere in the controller when the UPDATE_JUDGEMENT
  packet is not being sent.

A quick smoke test using build 6181 (prod) and 6189 (latest dev)
did not reproduce this bug.

**To Reproduce**: 

The steps to reproduce are unknown at this time.
(Smoke tests on both builds on a Windows 10 box did not reproduce the bug)

**Expected behavior**: 

Upon being judged all runs' status should change from
BEING_JUDGED to the judgement.

**Actual behavior**: 

Upon being judged all runs' status stays BEING_JUDGED.

**Workaround**: 

Exit the admin (or feeder), restart, the status/judgements
are correct.

**Environment**: 

**Log Info**:  

**Screenshots**:  

**Additional context**:

**Comment by clevengr** [comment]
I am not convinced that this bug is (necessarily) related to Shadow operations.  I'm almost certain we saw this happen in the PacNW contest (March 6, 2021) and there was no Shadow involved there at all.

**Comment by lane55** [comment]
John,

On Thu, Apr 29, 2021 at 08:30:19PM -0700, John Clevenger wrote:
> I am not convinced that this bug is (necessarily) related to Shadow operations.

  It is not.

  It was very clearly exposed/reproduceable during the shadow. 

  The bug is that the client is not receiving the UPDATE_JUDGEMENT packet,
  here is proof:

  1 - that is the packet aka judgement that updates the Run grid

  2 - What seemed like a bug in edit run was not.   The grid
     showed BEING_JUDGED but edit run showed the run Judged
     because the admin got a copy of the Run from the server.

  3 - we both saw that the packet viewer listing did not
     contain an UPDATED_JUDGEMENT incoming packet.

  4 - the server's data is up to date (proven when we restarted
     the admin/feeder and the judgements showed up properly).

  So the bug is somewhere in the controller when the UPDATE_JUDGEMENT
  packet is not being sen

> I'm almost certain we saw this happen in the PacNW contest (March 6, 2021) and there was no Shadow involved there at all.

  Correct, but that was AWS too.

Doug
