### ISSUE TITLE
edu.csus.ecs.pc2.core.transport.TransportException: Connection refused: connect

### ISSUE THREAD

**Issue by AlrightyTighty** [pc2ccs/pc2v9#294]
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**: please provide a clear and concise description of what the bug is.  
I'm current trying to set up a 1 site pc2css server on my computer to test for school. I assume the bug has something to do with how my firewall is configured. I'm not experienced at all with networking, so I'd appreciate the help.

**To Reproduce**: please describe, in order, the steps to reproduce the behavior:
      1. set your site 1 server IP to the server's IP
      2. run a team client

**Expected behavior**: please provide a description of what you *expected* to happen when you took the above steps:  
    The client would connect fine and the user would be able to log in

**Actual behavior**: please describe what _actually_ happened when you took the above steps:
    The GUI opens, but it has an error message "Unable to contact server, contact staff".

**Environment**: please complete the following information:
 - OS name and version under which the issue was detected (e.g. Windows 10 or Ubuntu 18.04): Windows 10
 - PC2 Version (e.g. 9.7.0):   9.7.0
 - Browser (if the bug is related to web-based team clients) (e.g. _Chrome Version 75.0.3770.142_ or _Safari Version 11.1.2_): N/A

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

> 220113 193314.173|INFO|main|setClientServerAndPort|setClientServerAndPort 73.77.26.230 parsed as 73.77.26.230 port 50002
220113 193314.174|INFO|main|info|Contacting server at 73.77.26.230:50002
220113 193314.174|INFO|main|connectToMyServer|Connecting to 73.77.26.230:50002
220113 193316.225|INFO|main|<init>|IO Exception:73.77.26.230
220113 193316.226|INFO|main|connectToMyServer|Could not ConnectToMyServer()
220113 193316.226|INFO|main|start|Exception contacting my server 
|edu.csus.ecs.pc2.core.transport.TransportException: Connection refused: connect
|    at edu.csus.ecs.pc2.core.transport.TransportManager.connectToMyServer (TransportManager.java:198)
|    at edu.csus.ecs.pc2.core.transport.connection.ConnectionManager.connectToMyServer (ConnectionManager.java:100)
|    at edu.csus.ecs.pc2.core.InternalController.start (InternalController.java:3105)
|    at edu.csus.ecs.pc2.Starter.main (Starter.java:50)

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.
![image](https://user-images.githubusercontent.com/97713800/149439786-b1cb6225-dc3c-42e8-8340-6da526ed9df4.png)
![image](https://user-images.githubusercontent.com/97713800/149439976-57fba876-e19b-4839-a5a3-33e055006c17.png)

**Additional context**: please add any other context about the issue here.

**Comment by AlrightyTighty** [comment]
Solved, I put the wrong IP in, haha. Sorry for the trouble!

**Comment by clevengr** [comment]
Glad to hear you solved it!   We were looking into things trying to see if we could spot any errors -- but of course we wouldn't recognize a "wrong" IP :)
