### ISSUE TITLE
Event Feed JSON report contains incorrect contest times in submissions

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#326]
**Describe the issue**: 
A contest was configured to run for 8 days, with a freeze length (duration) of 24 hours (i.e. freeze the scoreboard for the last day).  Several submissions were received within the freeze period, but when the Event Feed was input to the Resolver, the Resolver reported "0 pending runs".  

Examination of the Event Feed JSON report (which is what was used to generated the input to the Resolver) revealed the following event in the event feed:
```
{"type":"submissions", "id":"pc2-824", "op":"create", "data": {"id":"648","language_id":"C++-1491114644002074695","problem_id":"Hello-1","team_id":"430","time":"2022-03-01T21:30:16.735-08","contest_time":"21:28:47.332","entry_point":"Hello-1","files":[{"href":"/submissions/648/files"}]}}
```
The submission time for that run, as shown on the Admin, is 11368 (minutes).  That's 189 hours and 28 minutes.  That run should have had a "contest_time"  entry of something like 189:28:47 -- just a few hours before the end of the contest and WELL past the freeze point, which as shown by this JSON event:
```
{"type":"state", "id":"pc2-2", "op":"create", "data": {"started":"2022-02-22T00:01:00.005-08","ended":"2022-03-02T00:01:00-08","frozen":"2022-03-01T00:01:00.005-08","finalized":"2022-03-02T00:17:01.180-08"}}
```
was at 1 minute past midnight on march 1st (i.e., one minute into Tuesday -- 24 hours before the end of the contest.

The submission event has a "contest_time" of `21:28:47.332` which is on the first day of the contest; that's wrong.

**To Reproduce**:
Run a contest for multiple days, with a freeze duration of 24 hours.  Submit a run within the freeze period.  Generate an Event Feed JSON report and look at the submission time (contest time) in the submission event.

**Expected behavior**:
The submission time should be more than 24 hours.

**Actual behavior**: 
The submission time ("contest_time") will be less than 24 hours.

**Comment by lane55** [comment]
closing issue, already merged.
