### ISSUE TITLE
New ICPC Contest system wants results in CSV format not TSV

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#351]
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**: 
The newest flavor of the day ICPC website requires the results of a contest to be uploaded in CSV format with a very specific header (which they provide a template for).  The current system appears to only generate a TSV file from the Run Contest->Finalize tab. 

**To Reproduce**: 
Go to Run Contest->Finalize, and Click View->Save.  The file is in the format the old site accepted (TSV with "results 1" at the top).

**Expected behavior**: 
There should be an option to generate a CSV file (in addition to?) the TSV file with the following headers, as per the ICPC website:
teamId,rank,medalCitation,problemsSolved,totalTime,lastProblemTime,siteCitation,citation

**Actual behavior**: 
Only the results.tsv file is generated, and this is not accepted by the ICPC website.

**Environment**: please complete the following information:
 Ubuntu 20.04.1 LTS (Focal Fossa)
 Version 9.7.0 20210317 6181 (Wednesday, March 17 2021 06:30 UTC)

**Log Info**:  N/A

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**:
To workaround the issue, the resulting results.tsv file has to be massaged to work with the new ICPC system.  Change all tabs to commas.  Remove first line, add new header.
It is interesting to note that DOMJudge has the exact same issue - not sure about Kattis (DRC).

**Comment by lane55** [comment]
Some analysis, this is non-trivial in that the results.tsv has different content (not just format, content)
than results.csv.   There are additional fields that do not seem to be in the scoreboard XML (DSA XML),
so there is new logic to produce the two new fields in the DSA XML and all the testing involved
with that new logic.

There are two additional fields for each row:
     7 siteCitation,
     8 citation

results.tsv for each team returns 6 fields:
1 Reservation ID 24314 integer
2 Rank in contest 1 integer
3 Award gold string
4 Number of problems the team has solved 4 integer
5 Total Time 534 integer
6 Time of the last submission 233 integer

Whereas the CSV file returns 8 fields.
     1 teamId,
     2 rank,
     3 medalCitation,
     4 problemsSolved,
     5 totalTime,
     6 lastProblemTime,
     7 siteCitation,
     8 citation

**Comment by johnbrvc** [comment]
Right now, after exporting the results.tsv file, it requires someone to manually hand-edit the file to convert it to the new format.  The first 6 fields are essentially the same.  The last 2 are new, but not required, that is, empty fields appear to work fine (which is what used for our regional):
teamId,rank,medalCitation,problemsSolved,totalTime,lastProblemTime,siteCitation,citation
663908,3,Bronze Medal,11,964,195,,
662588,2,Silver Medal,12,923,187,,
658778,1,Gold Medal,13,1140,224,,
664362,4,Ranked,11,990,193,,

As an interim solution until a GUI is added for the extra citation fields, or, they can be imported from the ICPC system somehow (doubtful), it may make sense to just leave them blank, then, the local region can manually add those fields if they want to use them.  I believe they are only for the certificates that each contestant receives.  If they're empty, those fields are not printed I would imagine.  It should be easy to produce a CSV file that meets the minimum requirements - not a perfect solution, but it may be enough for most regions?

It may help to ask TPTB why this was done.

**Comment by troy2914** [comment]
what are the values for siteCitation and citation?   And is honorable a medal of a *citation?
