### ISSUE TITLE
DefaultScoringAlgorithm causes Null-pointer Exception when formatting team name on older profiles

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#361]
**Describe the issue**:  DefaultScoringAlgorithm gets Null-pointer exception causing a warning pop-up when starting the pc2admin client.

Standings tab is empty.

**To Reproduce**: 

Load an older profile before #254.  Run pc2admin.  

**Expected behavior**: 

No warning should be issued, 
and the standings in Standings tab should be generated properly.  

**Actual behavior**: See "To Reproduce"

A warning will pop-up about not being able to create the standings HTML. 

The Standings tab will have no standings rows.

This is due to a Null-pointer being returned from ContestInformation.getTeamScoreboardDisplayFormat().

**Environment**: PC2 V9.7.0 being loaded into newer version of Pc2

**Log Info**:  
220325 163703.740|WARNING|AWT-EventQueue-0|parseAndDisplay|Trouble creating or parsing SA XML 
|java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "origString" is null
|    at edu.csus.ecs.pc2.util.ScoreboardVariableReplacer.substituteDisplayNameVariables (ScoreboardVariableReplacer.java:79)
|    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.createStandingXML (DefaultScoringAlgorithm.java:701)
|    at edu.csus.ecs.pc2.core.scoring.DefaultScoringAlgorithm.getStandings (DefaultScoringAlgorithm.java:462)
|    at edu.csus.ecs.pc2.ui.StandingsPane.parseAndDisplay (StandingsPane.java:151)
|    at edu.csus.ecs.pc2.ui.StandingsPane$1.run (StandingsPane.java:195)
|    at java.awt.event.InvocationEvent.dispatch (InvocationEvent.java:318)

**Additional context**: A member variable, teamScoreboardDisplayFormat, was added by i-254 that causes deserialization of older class objects not to restore that field properly, and it is set to null.

**Comment by johnbrvc** [comment]
A quick and easy fix that should work going forward is to set the teamScoreboardDislayFormat member to ScoreboardVariableReplacer.TEAM_NAME if it is null in the accessor, getTeamScoreboardDisplayFormat().
Changing the serial number of the class could work too, but it would not make it possible to load older profiles or pc2zip data,
and maintaining this capability is desired:

public String getTeamScoreboardDisplayFormat() {
        if (teamScoreboardDisplayFormat == null) {
            teamScoreboardDisplayFormat = ScoreboardVariableReplacer.TEAM_NAME;
        }
        return teamScoreboardDisplayFormat;
    }

**Comment by lane55** [comment]
More details on the stacktrace/NPE.

ScoreboardVariableReplacer Line 79:  
        if (origString.indexOf("{:") != -1) {

   The origString is null so NPE, from:

DefaultScoringAlgorithm (DSA) Line 701:
    standingsRecordMemento.putString("teamName", ScoreboardVariableReplacer.substituteDisplayNameVariables(teamVarDisplayString, account, group)); 

The String teamVarDisplayString is null
DSA Line 617:
        String teamVarDisplayString = contestInformation.getTeamScoreboardDisplayFormat();

**Comment by lane55** [comment]
closing ticket, fix merged.
