### ISSUE TITLE
Event Feed JSON contains judgements with undefined acronyms.

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#387]
**Describe the issue**: 
In the 2022 PacNW contest, the Event Feed JSON output from PC2 was rejected by the Resolver, whose log showed the following:
```
2022.03.05 16:28.32 E Contest event feed has 31 unjudged submissions, cannot run
2022.03.05 16:28.32 E Submission ids: 40, 87, 146, 170, 197, 498, 508, 522, 575, 611, 872, ...
```
Looking at the Event Feed JSON for the contest shows the following entries related to Submission 40:
```
{"type":"submissions", "id":"pc2-246", "op":"create", "data": 
    {"id":"40","language_id":"C++-3918517525028210700","problem_id":"RiseandFall-1","team_id":"104","time":"2022-03-05T11:19:19.472-08",
     "contest_time":"00:19:19.473","entry_point":"F","files":[{"href":"/submissions/40/files"}]
    }
}
...
{"type":"judgements", "id":"pc2-2621", "op":"create", "data": 
    {"id":"Run-1923957307774372492","submission_id":"40","start_time":"2022-03-05T11:19:19.472-08","start_contest_time":"00:19:19.473",
     "judgement_type_id":"IO","end_time":"2022-03-05T11:19:00-08","end_contest_time":"00:19:00.000"
    }
}
```
So Submission 40, which the Resolver claims has "no judgement", actually DOES have a judgement, as shown above; the `judgement_type_id` for it is "IO" (Incomplete Output).

However, the Event Feed also contains the following:
```
{"type":"judgement-types", "id":"pc2-3", "op":"create", "data": {"id":"AC","name":"Accepted","penalty":false,"solved":true}}
{"type":"judgement-types", "id":"pc2-4", "op":"create", "data": {"id":"CE","name":"Compilation Error","penalty":false,"solved":false}}
{"type":"judgement-types", "id":"pc2-5", "op":"create", "data": {"id":"RTE","name":"Run-time Error","penalty":true,"solved":false}}
{"type":"judgement-types", "id":"pc2-6", "op":"create", "data": {"id":"TLE","name":"Time Limit Exceeded","penalty":true,"solved":false}}
{"type":"judgement-types", "id":"pc2-7", "op":"create", "data": {"id":"WA","name":"Wrong Answer","penalty":true,"solved":false}}
{"type":"judgement-types", "id":"pc2-8", "op":"create", "data": {"id":"EO","name":"Excessive Output","penalty":true,"solved":false}}
{"type":"judgement-types", "id":"pc2-9", "op":"create", "data": {"id":"OFE","name":"Output Format Error","penalty":true,"solved":false}}
{"type":"judgement-types", "id":"pc2-10", "op":"create", "data": {"id":"OCS","name":"Other - Contact Staff","penalty":true,"solved":false}}
```
and these are the ONLY judgement types defined in the Event Feed. So the actual problem is that there is no judgement type "IO" defined (which the Resolver then interprets as an "unjudged submission").

Investigation into the issue found that the PacNW contest was indeed configured with exactly (and only) the judgement types shown above.  However, when the CLICS Validator encounters a submission whose execution produces incomplete output (i.e., output that matches the judge up to a certain point but then stops), or produces NO output (which is just the extreme case of "incomplete output"), the Validator returns a `judgement.txt` string (in the "feedback" folder) of "Incomplete Output".  It returns this string irrespective of the fact that "Incomplete Output" is not one of the judgement types configured in the contest.

There is a class `JSONTool` containing a method `convertJudgementToJSON(Run)` which is used in a number of places to generate JSON representations of judgements associated with a given run (Submission).   Method `convertJudgementToJSON(Run)` invokes an external method `CLICSJudgementType.getCLICSAcronymFromDisplayText(String)` which accepts a judgement (result) string (such as "Incomplete Output", "Wrong Answer", or "accepted") returned by a Validator, and returns a corresponding CLICS acronym for the judgement result string.  

Method `CLICSJudgementType.getCLICSAcronymFromDisplayText(String)` contains a mapping of every known CLICS result string to a corresponding CLICS acronym.  However, _it does not pay attention to whether a result string corresponds to a result which is defined for the current contest_.  The result is that calls to this method can get back acronyms which are defined by CLICS (such as "IO") but which are _not_ defined in the current contest.  This is what caused the above issue at the PacNW contest.

It's not yet completely clear what the proper fix for this issue is (although there is a known workaround; see below).
Among the classes which invoke `JSONTool.convertJudgementToJSON(Run)` (and hence invoke `CLICSJudgementType.getCLICSAcronymFromDisplayText(String)`) are:  `services.core.EventFeedJSON`, `services.web.EventFeedStreamer`, and `services.web.JudgementService`.   Any code change which is an effort to fix this bug need to consider possible ramifications on all of these classes.

**To Reproduce**: 
- Start a server, loading `samps/contests/SumitHello`.
- Submit a program which produces _no output_ for the problem (`samps/src/nooutput.c` or `samps/src/NoOutput.java` will work).
- Generate an EventFeedJSON report; examine the listed "judgement_types" and the "judgement_type_id" for the submitted run in the report.

**Expected behavior**:  
The submission should have an acronym ("judgement_type_id") which exists in the list of "judgement_types" in the Event Feed.

**Actual behavior**: 
The submission has a "judgement_type_id" of "IO", which is not defined in the "judgement_types" for the contest.

**Environment**: 
 - Windows 10.1
 - PC2 Version:   any V9.5+ version up to the date this Issue was filed.

**Additional Information**: 
A workaround for this issue is to ensure that every possible return string from the validator being used is defined in the contest, by including it in the `reject.ini` file.  

Strings which can be returned by the CLICS Validator include:
- "Incomplete output"
- "Excessive output"
- "Incorrect output format"
- "Wrong Answer"
- "Runtime Error"
- "accepted"
- 
Strings which can be returned by the PC2 ("Internal") Validator include:
- "accepted"
- "No - Presentation Error"
- "No - Wrong Answer"
- "No - Run-time Error"
- "No - Indeterminant"

**Comment by lane55** [comment]
Fix bug - replace CLICSJudgementType.getCLICSAcronymFromDisplayText(resultString) that overrides 
the judgement acronym with a acronym that may not be in the model with code
that retrieves "the" assigned judgement acronym from the model which is saved with the Run.

The acronym from CLICSJudgementType.getCLICSAcronymFromDisplayText(resultString)  is replaced
if the judgement text/name any of the 98 judgement text in the CLICSJudgementType which in the
past has caused an invalid event feed.

For Judgement Mapping use/See #187

**Comment by lane55** [comment]
fix merged closing
