### ISSUE TITLE
On Judge UI add feature to execute all test cases if stop-on-first-failed-test-case is true

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#39]
**Feature Description**: 

On Judge UI add a feature to execute all tests cases if stop-on-first-failed-test-case is true.

**Have you considered other ways to accomplish the same thing?** 

The only way to execute all test cases would be to change
the Problem def and that potentially could cause more problems
and more load on auto judges if they start judging the same 
problem.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 

Add a button in the Test Results frame at the bottom named
Execute all with a tool tip of Execute all test cases.

**Additional context**: 

This was requested by a judge at the local CSUS contest.

**Comment by SamanwaySadhu** [comment]
I will look into this issue.
