### ISSUE TITLE
Confirmation dialog needed to Stop Shadowing

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#424]
Thank you for contributing a suggestion for a new feature in PC^2!  
In order to help us understand the proposed feature, please fill in the following fields:

**Is your feature request related to a problem?** 
On the Event Feeder Shadow Mode tab, if Shadowing is connected, and the Stop Shadowing button is pressed, a confirmation dialog should be presented to make sure that's what the user wants to do.

**Feature Description**:  
Accidentally hitting the "Stop Shadowing" button can cause a huge delay in keeping the contest in sync with the primary because it would require you to re-"Start Shadowing", and re-reading the entire event feed.

**Have you considered other ways to accomplish the same thing?** 
Avoid pressing the "Stop Shadowing" button accidently.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**
Create a pop-up confirmation dialog

**Additional context**:

**Comment by clevengr** [comment]
Closing after approval and successful merge of PR #454.
