### ISSUE TITLE
If shadow connection is lost to primary, an auto-reconnect should optionally be attempted

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#429]
**Describe the issue**: 
If there is a network disruption, it is possible for the shadow to lose its connection to the primary.  In this case, it should be possible to have the shadow automatically attempt to reconnect to the primary.   This can be a check-box option on the Shadow tab.  See also Issue #422 

Add information on the Shadow tab: the last connection date/time to the Primary CCS and some indication whether it is a connection (via Start Shadowing) or an automatic reconnection.
Naturally when a connection is dropped that should be logged, and when reconnected should be logged.
There should be a constant defined for how long in ms before the Shadow reconnects.

**To Reproduce**: 
Start shadowing to a primary.  Disrupt network connection (pull ethernet cable? change IP address?).  Restore network connection after a few minutes.  Notice exception in Feeder log.  No reconnect attempt is made and error is silently ignored.

**Expected behavior**: 
If (a new) "Reconnect on lost connection" checkbox is checked, the Feeder should attempt to reconnect to the primary to restore the connection. 

**Actual behavior**:
The lost connection is silently ignored an no further shadow updates occur.

**Environment**: please complete the following information:
 All

**Log Info**:  
220530 140811.764|SEVERE|RemoteEventFeedMonitorThread|run|Exception reading event from stream:
|java.io.IOException: Premature EOF
| at sun.net.www.http.ChunkedInputStream.readAheadBlocking (ChunkedInputStream.java:568)
| at sun.net.www.http.ChunkedInputStream.readAhead (ChunkedInputStream.java:612)
| at sun.net.www.http.ChunkedInputStream.read (ChunkedInputStream.java:699)
| at java.io.FilterInputStream.read (FilterInputStream.java:133)
| at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read (HttpURLConnection.java:3510)
| at java.io.BufferedInputStream.read1 (BufferedInputStream.java:290)
| at java.io.BufferedInputStream.read (BufferedInputStream.java:351)
| at sun.nio.cs.StreamDecoder.readBytes (StreamDecoder.java:284)
| at sun.nio.cs.StreamDecoder.implRead (StreamDecoder.java:326)
| at sun.nio.cs.StreamDecoder.read (StreamDecoder.java:178)
| at java.io.InputStreamReader.read (InputStreamReader.java:181)
| at java.io.BufferedReader.fill (BufferedReader.java:161)
| at java.io.BufferedReader.readLine (BufferedReader.java:326)
| at java.io.BufferedReader.readLine (BufferedReader.java:392)
| at edu.csus.ecs.pc2.shadow.RemoteEventFeedMonitor.run (RemoteEventFeedMonitor.java:590)
| at java.lang.Thread.run (Thread.java:829)
220530 141044.221|INFO|AWT-EventQueue-0|stopShadowing|Shadowing stopped
220530 141046.977|INFO|AWT-EventQueue-0|start|Starting shadowing for URL 'https://nac22.kattis.com/clics-api/contests/nac22/' using login 'niemela'

**Additional context**: 
Care has to be taken here since reconnecting to the primary implies that the ENTIRE event feed is reprocessed.  Technically, this should not be an issue, other than taking a long time, however, there should be a way skip previously processed records.

**Comment by lane55** [comment]
Some requirements to consider:
Add a JList to the shadow pane, each time there is a dis/reconnection add a row
<reconnection count> <event token  >  <date/time, new Date()>

**Comment by lane55** [comment]
Note to use since_token on event feed API
/event-feed?since_token=xx

**Comment by lane55** [comment]
I have not reviewed the PR, I am focusing on requirements/expectations rather than "as is".

This seems to be missing examples for testing.   What are examples of the messages added to the JLIst.  (Screen caps would be unhelpful)

What would be example messages for?
connect 
disconnect 
socket error disconnect
reconnect ?

There is missing information on the Test Connection - what was the URL for this test ?  If we do a typo, there is no indication of the URL for a failure.  Add the URL at the end of the string.

**Comment by lane55** [comment]
For each event there should be a log message that matches the JList info.
If there are other log messages they should remain as is so when we
compare earlier logs and maybe get a better understanding of when the
events happened.
