### ISSUE TITLE
Autojudges hang if a run's related files are missing

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#438]
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**:
When autojudging, If the files for a run can not be found  all autojudges hang waiting for the files.

**To Reproduce**: 
(From @ashoos72 ):
Start a server
Start admin
Configure a few teams/judges
Configure 1 hello world problem with an answer file and computer judging (using pc2 diff or whatever)
Configure java
Configure 1 aj for the problem
start the contest

Start a team
submit three hello world solutions

go to a server db.1 folder and delete s1r2.files (the run files for submission #2)

start the AJ
You will see the AJ judge the first submission and then hang on submission #2.

**Expected behavior**: 
The AJ should not  hang if a run's files are not present

**Actual behavior**: 
All AJ's attempt to fetch the same run (since the run state is queued for computer judgement.  They all get stuck
waiting for the run's files, which will never come.

**Environment**: 
All.

**Log Info**:  
220527 141857.478|INFO|Thread-158478|info|sendToClient b4 to JUDGE10 @ site 1 Packet[RUN_NOTAVAILABLE] #22332 SERVER0 @ site 1 -> JUDGE10 @ site 1
220527 141857.479|INFO|Thread-158525|checkoutRun|runUnavailableException Client null can not checked out run 1340 (site 1)
22

**Screenshots**:  
**Additional context**:
This was noticed during the ACPC kickoff contest in June 2022.

**Comment by johnbrvc** [comment]
Initial testing confirms that Sam's proposed fix does prevent the AJ's from hanging.  The damaged run is in fact converted to status "NEW" so it wont be touched by any  autojudges.  Slightly modified information message in the SERVER log shows:

**220607 091537.134|INFO|Thread-30|dumpPacket|  From: JUDGE10 @ site 1, oJUDGE10 @ site 1 (john-lenovo @ 192.168.3.244) (Contest Id: Actual-7703622227645370927)
220607 091537.134|INFO|Thread-30|dumpPacket|    To: SERVER0 @ site 1
220607 091537.134|INFO|Thread-30|dumpPacket|   key: CLIENT_ID is: edu.csus.ecs.pc2.core.model.ClientId JUDGE10 @ site 1
220607 091537.134|INFO|Thread-30|dumpPacket|   key: READ_ONLY is: java.lang.Boolean false
220607 091537.134|INFO|Thread-30|dumpPacket|   key: COMPUTER_JUDGE is: java.lang.Boolean true
220607 091537.134|INFO|Thread-30|dumpPacket|   key: RUN is: edu.csus.ecs.pc2.core.model.Run Run 1349 QUEUED_FOR_COMPUTER_JUDGEMENT 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674
_220607 091537.431|INFO|Thread-30|checkoutRun|contest.getRunFiles can not get files for run 1349 (settng to status NEW): profiles\Pd3b0764a-5173-4f69-913a-0dbdc9131770\db.1\s1r1349.files (The system cannot find the file specified)_
220607 091537.670|DEBUG|Thread-30|logDebugMessage|Run Event Run 1349 NEW 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674 CHANGED** 

The judge log shows:
**220607 091537.680|INFO|Thread-10|info| receiveObject(S) start got Packet[RUN_NOTAVAILABLE] #19 SERVER0 @ site 1 -> JUDGE10 @ site 1
220607 091537.680|INFO|Thread-10|dumpPacket|Packet RUN_NOTAVAILABLE (Seq #19, o#19 ) recieveObject
220607 091537.680|INFO|Thread-10|dumpPacket|  From: SERVER0 @ site 1, oSERVER0 @ site 1 (john-lenovo @ 192.168.3.244) (Contest Id: Actual-7703622227645370927)
220607 091537.680|INFO|Thread-10|dumpPacket|    To: JUDGE10 @ site 1
220607 091537.681|INFO|Thread-10|dumpPacket|   key: RUN is: edu.csus.ecs.pc2.core.model.Run Run 1349 NEW 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674
220607 091537.681|INFO|Thread-10|info|handlePacket start Packet[RUN_NOTAVAILABLE] #19 SERVER0 @ site 1 -> JUDGE10 @ site 1
220607 091537.681|INFO|Thread-10|dumpPacket|Packet RUN_NOTAVAILABLE (Seq #19, o#19 ) handlePacket
220607 091537.681|INFO|Thread-10|dumpPacket|  From: SERVER0 @ site 1, oSERVER0 @ site 1 (john-lenovo @ 192.168.3.244) (Contest Id: Actual-7703622227645370927)
220607 091537.681|INFO|Thread-10|dumpPacket|    To: JUDGE10 @ site 1
220607 091537.681|INFO|Thread-10|dumpPacket|   key: RUN is: edu.csus.ecs.pc2.core.model.Run Run 1349 NEW 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674
220607 091537.681|INFO|Thread-10|runChanged|RunsPane.RunListener: Action=RUN_NOT_AVAILABLE; DetailedAction=null; msg=null; run=Run 1349 NEW 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674; runFiles=null
220607 091537.681|WARNING|Thread-10|runChanged|Reply from server: requested run not available
220607 091537.682|INFO|Thread-10|runChanged|RunsPane.RunListener: Action=RUN_NOT_AVAILABLE; DetailedAction=null; msg=null; run=Run 1349 NEW 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674; runFiles=null
220607 091537.682|INFO|Thread-7|info|Unable to fetch run Run 1349 QUEUED_FOR_COMPUTER_JUDGEMENT 321 min 19260000ms from TEAM1 @ site 1 id Run--4072246608623555092 problem A-Football_Scoring--9160049964803627853 lang GNU_C++--5301923090542877674
220607 091537.682|WARNING|Thread-10|runChanged|Reply from server: requested run not available**

The "read-only" case has to be "fixed" as well, since the "Edit" Run (Administrator view) also hangs fetching the run but you can 
cancel out of it - although you still have no idea was happened.  If you do a View Source, nothing happens except a message saying "Preparing to display source..."  I'd like to see if there's  way to combine the code that fetches the runlist rather than duplicate for both readOnly and not readOnly.

I still believe the code is wrong AutoJudgingMonitor.runChanged where it processes the response of RUN_NOT_AVAILABLE, and we should check that out.

**Comment by johnbrvc** [comment]
There are several places in the code that use contest.getRunFiles() and do not catch exceptions (FileNotFoundException in this case).  Several places DO catch the exception and deal with appropriately, ex. in Judge, if you go to judge a run manually where the runfiles are missing, you'll receive an appropriate error message.  Other places, such as Administrator "edit" or "view source" will cause the server to generate an exception:

220607 095225.093|INFO|Thread-70|info|Exception in processPacket, check logs 
|java.io.FileNotFoundException: profiles\Pd3b0764a-5173-4f69-913a-0dbdc9131770\db.1\s1r1351.files (The system cannot find the file specified)
|    at java.io.FileInputStream.open0 (FileInputStream.java:-2)
|    at java.io.FileInputStream.open (FileInputStream.java:195)
|    at java.io.FileInputStream.<init> (FileInputStream.java:138)
|    at java.io.FileInputStream.<init> (FileInputStream.java:93)
|    at edu.csus.ecs.pc2.core.security.FileSecurity.readObjectFromFile (FileSecurity.java:613)
|    at edu.csus.ecs.pc2.core.security.FileSecurity.readSealedFile (FileSecurity.java:452)
|    at edu.csus.ecs.pc2.core.security.FileSecurity.load (FileSecurity.java:627)
|    at edu.csus.ecs.pc2.core.list.RunFilesList.getRunFiles (RunFilesList.java:164)
|    at edu.csus.ecs.pc2.core.list.RunFilesList.getRunFiles (RunFilesList.java:192)
|    at edu.csus.ecs.pc2.core.model.InternalContest.getRunFiles (InternalContest.java:1570)
|    at edu.csus.ecs.pc2.core.PacketHandler.requestFetchedRun (PacketHandler.java:1508)
|    at edu.csus.ecs.pc2.core.PacketHandler.handleOtherPacketTypes (PacketHandler.java:386)
|    at edu.csus.ecs.pc2.core.PacketHandler.handlePacket (PacketHandler.java:268)
|    at edu.csus.ecs.pc2.core.InternalController.processPacket (InternalController.java:2200)
|    at edu.csus.ecs.pc2.core.InternalController.receiveObject (InternalController.java:1591)
|    at edu.csus.ecs.pc2.core.transport.TransportManager$1.run (TransportManager.java:336)
|    at java.lang.Thread.run (Thread.java:750)
220607 095225.093|INFO|Thread-70|info|Exception in processPacket for Packet[FETCH_RUN] #14 ADMINISTRATOR1 @ site 1 -> SERVER0 @ site 1
220607 095225.093|INFO|Thread-70|info|receiveObject end   got edu.csus.ecs.pc2.core.packet.Packet

since runFiles is not protected by a try/catch in this case (PacketHandler.requestFetchedRun()).  
Is this a separate issue?  to go through and fix all occurrences of getRunFiles to be protected by try/catch?
I count 3 places that are unhandled: ExtractRuns, InternalController.fetchRun, PacketHandler
The InternalController.fetchRun is called by RunPane and RunTablePane.

Administrator->Edit Run hangs if a run is not available.  The server does send back a RUN_NOTAVAILABLE, but the Edit Run window just sits there with a spinning cursor.  The Admin does receive the RUN_NOTAVAILABLE but apparently doesnt know what to do.  This may be a separate issue too.

**Comment by troy2914** [comment]
Agreed those items should be separate issues.

**Comment by troy2914** [comment]
Btw, agreed the read-only section of the server also needs the same type of changes, and that should be covered by this issue.

**Comment by clevengr** [comment]
@johnbrvc Thanks so much for your quick and very helpful support in getting this bug squashed.  

One note, which @troy2914 mentioned but didn't explain in detail:  when you submit a PR, if the PR is being proposed as a fix to an issue (rather than some sort of intermediate work that's already known to be only partial intermediate work towards an eventual fix), it's helpful to include the phrase "Fixes #xxx", where "xxx" is the number of the issue which the PR is supposed to fix.  This causes GitHub, when the PR is ultimately merged, to automatically close the issue (otherwise, someone has to go back and manually close it, like I'm doing now :)

Closing after the merge of PR #440.
