### ISSUE TITLE
Multiple entries are duplicated in pc2rui Plugins list

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#441]
**Describe the issue**: please provide a clear and concise description of what the bug is.  
The `pc2rui` ReportsUI module contains a `UI Plugins` tab that displays a drop-down list of all PC2 UIPlugins and allows selecting a plugin and either opening it in a new window or adding it as a tab to the `pc2rui` GUI.  The plugin drop-down list contains _two_ entries for `Clarifications Table Pane`.  The first one was (probably) intended to be "Clarifications Pane" and intended to display the old "ClarificationsLegacyPane" which used MCLB instead of JTable.

**To Reproduce**: 
- Start the pc2rui module.
- Login as an administrator.
- Select the "UI Plugins" tab.
- Click the drop down box and scroll down.
- Observe that there are two identical entries for `Clarifications Table Pane`, and that when selected they produce identical results.

**Expected behavior**: 
There should not be two identical entries producing identical results.  The first one should probably be "Clarifications Pane" (or maybe "Clarifications Legacy Pane".

**Actual behavior**: 
See above.

**Environment**:
All.

**Screenshots**:  
![image](https://user-images.githubusercontent.com/9256691/172480801-bd4008fd-7dce-4a03-a060-9e618ad7d3c8.png)

**Comment by johnbrvc** [comment]
You will note in the screen shot that "Clarifications Pane" is already there (legacy one).  It's just that there are 2 of the "Clarifications Table Pane", so the second one should just be removed.  No need change it or add one for Legacy Clarifications Pane.

**Comment by lane55** [comment]
The convention is to add the work "Table" to the new tabs that use a JTable.

**Comment by johnbrvc** [comment]
Actually, there are others that are duplicated too:
Accounts Table Pane
Event Feed Server Pane
Runs Table Pane
Standings Table Pane
I must have re-added some of the new ones, but not Event Feed Server Pane.  All these duplicates can be removed at the same time.  One line fix changes to a 5 line fix.

**Comment by clevengr** [comment]
Updated issue description to match the additional issues pointed out by JohnB.

**Comment by lane55** [comment]
Yes, let’s change scope to “no duplicate panes”.  I will update the bug title.
