### ISSUE TITLE
Change AJ fetch next unjudged run order 

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#444]
**Is your feature request related to a problem?**

AJs should request runs based on earliest TIME, not site or runId.   Currently the AJ fetches all runs in model,
sorts them by site # and run id then fetches the first 

**Feature Description**: please provide a clear and concise description of the proposed feature:  

Change the sort to by run elapsed time (ms), then run id, then site id.   It is very likely that the elapsed ms will
always be different and the secondary and tertiary comparisons will not be necessary

**Have you considered other ways to accomplish the same thing?**  

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** If so, please describe.  

Add new Comparator to sort runs.

**Additional context**:

**Comment by lane55** [comment]
Note that to test all one needs to do is start all clocks, submit runs to site 2, pause for a minute or two submit
runs to site 1, then start an AJ.   Existing code will ignore elapsed time and fetch runs from site 1 first.
The fix will judge runs based on elapsed time (ms) and will judge runs from site 2 first.

**Comment by clevengr** [comment]
The fix for this was implemented in PR #447 which was approved and merged.  However, the PR did not include the requisite GitHub keyword to auto-close the Issue; closing it manually now.
