### ISSUE TITLE
Document ReportsView (ReportsUI, pc2rui) feature

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#449]
**Is your feature request related to a problem?** 

No.

**Feature Description**: 

Add documentation for ReportsView #417

The team should discuss where new documentation should be added and how.
Add to the the Admin Guide PDF?  The wiki ?

Is there a way to have a single source markup language to generate the PDF?

**Have you considered other ways to accomplish the same thing?** 

Yes, need new doc.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

**Additional context**:

**Comment by clevengr** [comment]
```
The team should discuss where new documentation should be added and how.
Add to the the Admin Guide PDF? The wiki ?
```
I will add things to the Admin Guide.  I'm not sure how to go about adding docs to the Wiki -- that is, what would the breakdown of the Wiki pages be?

```
Is there a way to have a single source markup language to generate the PDF?
```
You mean to have a single source that will generate both the Admin Guide PDF and a wiki Page?

**Comment by lane55** [comment]
Documentation added to Admin Guide in Appendix S – The pc2rui Tool 
Doc complete closing issue
