### ISSUE TITLE
Add entry_point processing when read from event feed (CLICS and Shadow implementation)

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#46]
**Feature Description**: 

For shadow and in the contest model for a Run, add an entry point.

The JSON CLICS EF from a primary supplies the entry point 
for the team's submission.   PC2 solved this in
a different way by the user selecting the entry point
file.  Using the EF the primary CCS specifies.

This entry point would be used in Executable class to
run/execute the correct program/class if there is
more than one team submission file (in a Run)

**Have you considered other ways to accomplish the same thing?** 

Yes. N/A

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 

Add entry point char [] field in Run.
When executing if entry point defined use that as the pc2 main file.

**Additional context**: 

none.

**Comment by lane55** [comment]
Pushed code onto i_46_add_support_for_EF_entry_point in fork git@github.com:lane55/pc2v9.git
Added code to populate Run entryPoint and replace {:basename} in executable with entry point (if not null)

**Comment by lane55** [comment]
How can a shadow be setup to test this?

**Comment by lane55** [comment]
Is this change necessary?   Has there been any event feed where the class name is different than
the entry_point ?

**Comment by clevengr** [comment]
`Has there been any event feed where the class name is different than
the entry_point ?`  Yes.  This occurs when a team submits a Java/Kotlin program using a package.

**Comment by johnbrvc** [comment]
> Pushed code onto i_46_add_support_for_EF_entry_point in fork [git@github.com](mailto:git@github.com):lane55/pc2v9.git Added code to populate Run entryPoint and replace {:basename} in executable with entry point (if not null)

I looked on the @lane55 pc2 repo and could not find any push for i_46_add_support_for_ef_entry_point.  Did I miss something?  @lane55 are you going to address this issue?  If not, I can take a look at it.

**Comment by lane55** [comment]
re-pushed branch i_46_add_support_for_EF_entry_point
