### ISSUE TITLE
Update documentation in prep for 9.8 release

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#460]
This Issue is for tracking changes to the Admin Guide and WhatsNew documents in preparation for generating a 9.8 Release Candidate and subsequently a stable release.

**Comment by clevengr** [comment]
Reopened to support updates to doc related to PR #459 and PR #524.

**Comment by troy2914** [comment]
Is this issue completed?

**Comment by clevengr** [comment]
> Is this issue completed?

No; the issue is being left open until the documentation updates for 9.8 are finished.  The final PR for that (whenever it comes) should be used to close the issue.
