### ISSUE TITLE
Add --nologging option to disable all logging

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#489]
**Is your feature request related to a problem?** 

This only applies to the Admin GUI.  When large numbers of
runs are rapidly added to the system (via JMeter) the
Admin becomes unresponsive.   It was found that the I/O methods during
logging were being blocked causing a bottleneck and the Admin
became unresponsive.

**Feature Description**: 

Add command line option option to not add lines to the log.

By default log to log files.

If --nologging option present, do not add any lines to the log files.

**Have you considered other ways to accomplish the same thing?** 

Yes, no work around found.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 

Add a --nologging option, when present do not write any log records/lines.

The log files will be created but they will stay at zero bytes in size.

**Additional context**:

**Comment by clevengr** [comment]
The code for this was merged; not sure why it didn't get closed automatically (missing "fixes" in PR?)  Closing.
