### ISSUE TITLE
Add --nostandings to not load StandingsPane and HTML Standings pane

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#490]
**Is your feature request related to a problem?** 

While doing stress testing (lots of runs) on the Admin, the
Admin GUI was updating so slowly that effectively the Admin
was unresponsive.

One cause for the slow down was the Standings and Standings HTML panes .
So to avoid this problem, while a better solution is found/implemented
providing a way to not load those panes is needed.

The cause seems to be the recalculation of the scoring (via the DSA)
for each run judgement that is received.   Both panes recalculate
the score to show a live update of the standings.

**Feature Description**: 

By default load the Standings and Standings HTML panes.

If the --nostandings command line option is specified do not
load the Standings and Standings HTML panes.

**Have you considered other ways to accomplish the same thing?** 

Yes, other ways.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add the option --nostandings, if present do not load
the Standings and Standings HTML panes.

**Additional context**: 

This was found during a stress test where 500 runs were added
to the system "at the same time"

**Comment by clevengr** [comment]
The code for this was merged; not sure why it didn't close automatically (missing "fixes" in PR?)   Closing.
