### ISSUE TITLE
Add doc for command line option --remoteServer

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#498]
**Is your feature request related to a problem?** 

Missing doc on --remoteServer server command line option in
PC^2 Version 9.8 Contest Administrator’s Installation and Configuration Guide

**Feature Description**: 

The --remoteServer host[:port] option is an override for the pc2v9.ini entry
remoteServer.   port by default is the default pc2 port 50002.

```
[server]
# if this server isn't the first, the remote server to which this server should connect
remoteServer=host
```

The usage shows the command line options
```
$ bin/pc2server --help
Usage: Starter [--help] [-F filename] [--server] [--first] [--login <login>] [--password <pass>] [--load <dir>|<file> ] [--skipini] [--nologging]
[--ini filename] [--contestpassword <pass>] [--nogui] [--nostandings] [--remoteServer <remoteHostname> --proxyme][--ui classname]

```
**Have you considered other ways to accomplish the same thing?** 

nay good sir

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

No, but there is a question, does this get added to the admin PDF for the wiki ?

**Additional context**:

**Comment by clevengr** [comment]
The use of **--remoteServer** option is already documented in the Admin Guide; discussion can be found on pages 17 & 21, with a full description in Appendix A (p 99) and further references in Appendices B & C.  Therefore, I'm marking this Issue "Invalid" because it asks for something that's already completed.

**Comment by lane55** [comment]
Marking the issue valid because there is no documentation for --remoteServer nor --proxyMe command line options per the server usage

While the use of remoteServer in the .ini is well documented,
There is no documentation describing the command line options.

**Comment by clevengr** [comment]
The "Feature Description" for this Issue says:
```
The --remoteServer host[:ip] option is an override for the pc2v9.ini entry
remoteServer. ip by default is the default pc2 port 50002.
```
Is `host[:ip]` a typo -- should it be `host[:port]`?

**Comment by lane55** [comment]
It is a typo.   Updated description
