### ISSUE TITLE
Shadow unable to fetch files for submission(s)

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#528]
**Describe the issue**: 

When the shadow attempts to fetch files the DOMJudge CCS API,fails to return the files (zip).

The file is fetched by pc2 shadow using a URL of the form:
http://<IPADDR>/domjudge/api/v4//contests/2/submissions/1/files
That will fail, the shadow is configured with: http://<IPADDR>/domjudge/api/v4/ for the Primary CCS URL field

The URL that will succeed is (This is per the CCS API Spec).
http://<IPADDR>/domjudge/api/v4/contests/2/submissions/1/files

Note that there is one slash after the /v4 in the path. Note that Kattis does fetch files given the URL 

**To Reproduce**: 

todo: State Version of DOM Judge
todo: state version of pc2

Configure both DOM Judge and pc2 as shadow

todo: configure DOM Judge
* In Config, set Data Source field to Configuration Data External   (the default is All Local, which will not output the latest CCS EF)

todo:: configure pc2 as shadow, start shadowing

**Expected behavior**: 

The files for the submission should be fetched and submitted to pc2 server.

**Actual behavior**: 

todo assuming: Files not fetched and the submission could not be added to the pc2 server.

See Log info below for example of exception/error message

**Environment**: 

**Log Info**: 

upon failure to read API end point
 
220830 172111.227|INFO|RemoteEventFeedMonitorThread|log|Fetching files from remote system using id 1
220830 172111.246|WARNING|RemoteEventFeedMonitorThread|log|Exception processing event: {"id":"59","type":"submissions","op":"create","data":{"language_id":"cpp","time":"2022-08-30T16:28:01.626-04:00","contest_time":"14553:28:01.626","team_id":"4","problem_id":"3","id":"1","external_id":null,"entry_point":null,"files":[{"href":"contests/2/submissions/1/files","mime":"application/zip"}]},"time":"2022-08-30T16:28:01.680-04:00"}
|java.lang.RuntimeException: java.io.FileNotFoundException: http://10.0.0.169/domjudge/api/v4/contests/2//submissions/1/files
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:281)
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:250)
|    at edu.csus.ecs.pc2.shadow.RemoteEventFeedMonitor.run (RemoteEventFeedMonitor.java:369)
|    at java.lang.Thread.run (Thread.java:750)
**Screenshots**:  

**Additional context**:

**Comment by johnbrvc** [comment]
Here are the log file entries for the feeder1 when the fetch of a submission's files failed:

```
220830 172111.227|INFO|RemoteEventFeedMonitorThread|log|Fetching files from remote system using id 1
220830 172111.246|WARNING|RemoteEventFeedMonitorThread|log|Exception processing event: {"id":"59","type":"submissions","op":"create","data":{"language_id":"cpp","time":"2022-08-30T16:28:01.626-04:00","contest_time":"14553:28:01.626","team_id":"4","problem_id":"3","id":"1","external_id":null,"entry_point":null,"files":[{"href":"contests/2/submissions/1/files","mime":"application/zip"}]},"time":"2022-08-30T16:28:01.680-04:00"}
|java.lang.RuntimeException: java.io.FileNotFoundException: http://10.0.0.169/domjudge/api/v4/contests/2//submissions/1/files
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:281)
|    at edu.csus.ecs.pc2.shadow.RemoteContestAPIAdapter.getRemoteSubmissionFiles (RemoteContestAPIAdapter.java:250)
|    at edu.csus.ecs.pc2.shadow.RemoteEventFeedMonitor.run (RemoteEventFeedMonitor.java:369)
|    at java.lang.Thread.run (Thread.java:750)

```
