### ISSUE TITLE
Scoreboard JSON update to CLICS 2022-07

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#535]
**Is your feature request related to a problem?** 

Yes, the scoreboard JSON (pc2 API / CLICS API scoreboard)
has not been updated to CLICS 2022-07 version/contents

**Feature Description**: 

Add header attributes, TODO list new attributes
Change JSON hiearchy, move current JSON into "rows" object under header?.

_Originally posted by @johnbrvc in https://github.com/pc2ccs/pc2v9/issues/534#issuecomment-1248016087_

The JSON format has also changed.  As per Tim Deboer, "...[A new parent item was added] in with some “header” attributes and moving the object you have now into a “rows” child object."  
As per: [https://ccs-specs.icpc.io/2022-07/contest_api#scoreboard](url)  The current JSON format is evidently from the very first CLICS API before 2019. 
TIm also said he "looked at the code and I *think* the CDS will handle the old or new formats, so it’s probably fine for now. "

**Have you considered other ways to accomplish the same thing?** 

Yes, there are none.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

There are at least three methods in pc2 where the scoreboard JSON is created, pick the right one, and update it per the description

**Additional context**: 

All current scoreboard JSON are created using multiple NSA and DSA methods,
here are some there may be more.
* ScoreboardJsonUtility.createScoreboardJSON 
* ContestAPIStandingsJSON.createJSON 
* StandingsJSON.createJSON

**Comment by troy2914** [comment]
this was completed with #811
