### ISSUE TITLE
event feed entry_point not used 

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#545]
**Describe the issue**: 

The entry_point event feed submission event field is not
being used to specify the class name for java submissions.

**To Reproduce**: 

**Expected behavior**: 

**Actual behavior**: 

**Environment**: 

**Log Info**:  

**Screenshots**:  

**Additional context**:

**Comment by clevengr** [comment]
This appears to be a duplicate of Issue #248, which in turn was already flagged as being suspected as a duplicate of Issue #46.  

If these are indeed duplicates, please close at least one (preferably two) of them.  If they are NOT duplicates, please change both the Issue Titles and the Issue Descriptions to differentiate the issues.

**Comment by lane55** [comment]
closing as duplicate.
