### ISSUE TITLE
Update assignment of team name from event feed from name and display_name fields

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#546]
**Is your feature request related to a problem?** 

Yes, need to update load/compare of team name from Primary EF

**Feature Description**: 

Chagne to use display_name if defined,
if not defined use name field.

**Have you considered other ways to accomplish the same thing?** 

n/a

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

**Additional context**:

**Comment by johnbrvc** [comment]
Closed as part of PR #531
