### ISSUE TITLE
Does not handle per-problem output limit, always uses contest global getMaxFileSize()

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#564]
**Describe the issue**: 
The newer problem package format, as described here: [https://icpc.io/problem-package-format/spec/problem_package_format#problem-metadata](url) allows a per-problem output file size limit (**output** key) to be specified.  Currently, PC2 does not handle this, and always uses the system wide default value in the contest object.

**To Reproduce**: 
Read a problem package "**problem.yaml**" file that contains an **output** key that has a different value than the default PC2 output limit.  The problem will still use the PC2 default value, not the per-problem value.

**Expected behavior**: 
The maximum output generated for the problem should be set to the per-problem limit, if it is present, otherwise, use the default PC2 value.

**Actual behavior**: 
The default PC2 value is always used.

**Environment**: 
All.

**Log Info**: 
N/A 

**Screenshots**:
N/A

**Additional context**: 
Based on a discussion with @clevengr on 2022-10-14:
Update the **core.model.Problem.java** class to have its own **maxFileSize** value, which can have a default value of 0.
Add accessor (and mutator) methods: **getMaxFIleSize** and **setMaxFileSize** to **Problem.java** (much like **timeOutInSeconds**)
Change **core.execute.Executable.java getMaxFileSize()** method to first check the problem model (**problem.getMaxFileSze()**), and if non-zero, use that as the output size limit, otherwise, return what it does now, **contest.getContestInformation().getMaxFIleSize()**.
Update problem configuration GUI to allow display and configuration of **MaxFileSize** on a per-problem basis with a checkbox to enable using the per-problem value.
Update the reading of **problem.yaml** on the loading of a contest configuration to pay attention to and handle the **output** key.

**Comment by clevengr** [comment]
I do not understand the purpose or intent of applying the label "Continuous Improvement" to this Issue.   The issue describes a feature which is specified by the CLICS standard but which PC2 doesn't implement.  If that's the criteria for identifying something as "Continuous Improvement", it seems like that applies to nearly every change we make (whether CLICS-driven or not).  Isn't every single change we make to the system for the purpose of "continuous improvement" of the system?  (I'm not trying to be disingenuous here; I'm saying that I don't understand the underlying meaning/intent of the "CI" label -- if it applies to something like this, how does it not apply to essentially everything we do?)

For clarity, what I *thought* we were using the "CI" notation for was when we were working on some specific (posted, numbered) Issue and we came across something else -- usually very minor -- that "ought to be fixed" but was so minor that it wasn't worth identifying as a "separate issue" and for which it was pretty clear that if it didn't get fixed when a developer was sitting there looking at it it was extremely unlikely to ever get fixed on its own, we would go ahead and fix it as part of the issue being worked on (even if it wasn't truly directly related to that issue), and then identify the reason/justification for making an "unrelated change" as "continuous improvement".  But that's clearly a completely different usage than its application here to this issue -- hence my statement that I don't understand what the purpose of identifying this Issue as "Continuous Improvement" is...

**Comment by lane55** [comment]
Note that the spec indicates the override in problem.yaml is
limits: 
   output: 8
there is no default value, it seems.

**Comment by clevengr** [comment]
> Note that the spec indicates the override in problem.yaml is limits: output: 8 there is no default value, it seems.

According to the spec (at https://icpc.io/problem-package-format/spec/problem_package_format#limits), the default is "system default" and "typical system default = 8".

**Comment by lane55** [comment]
I stated "seems" because there is no specified required hard default value, ex 12.   There is 
no statement that the default must be 12 (or the like).

**Comment by lane55** [comment]
Current PR meets the spec

**Comment by clevengr** [comment]
> I stated "seems" because there is no specified required hard default value, ex 12. There is
no statement that the default must be 12 (or the like).

Yep; I agree  this is a weird spot in the spec.  I'm pretty sure this is an artifact of the spec haven't been initially written by the Kattis team; the reference to "system default" is probably talking about their system.  I think we can take whatever we want (like, 512) as the "default".
