### ISSUE TITLE
Create a scoreboard.json for CLICS 2022-07 Report

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#590]
**Is your feature request related to a problem?** 

Create a scoreboard.json for CLICS 2022-07

**Feature Description**: 

Create a new report that will create CLICS 2022-07 scoreboard.json

**Have you considered other ways to accomplish the same thing?** 

n/a

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add a new report.

**Additional context**:

**Comment by troy2914** [comment]
This was completed under #811
