### ISSUE TITLE
Add tool to compare awards data/json

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#592]
**Is your feature request related to a problem?** 

Augomate awards.json comparison

**Feature Description**: 

Add a tool to compare two awards.json files

**Have you considered other ways to accomplish the same thing?** 

Yes, manual repair diff is challenging

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add a tool to compare, 

**Additional context**:

**Comment by clevengr** [comment]
It appears this is a duplicate of the PR work being done under Issue #760.  If so, this issue should be marked as a duplicate, and then closed.

**Comment by clevengr** [comment]
Doug agreed this is a dup of #760 and should be closed.
