### ISSUE TITLE
Add an interim compile time limit per language

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#607]
**Is your feature request related to a problem?** 

Yes, some team's source takes an excessive amount of time to compile
(ex. large source files, or requiring large amounts of time to compile)

**Feature Description**: 

Add a global compile time limit in ms.

Return a CE ??  if a team's srouce takes too long to compile

**Have you considered other ways to accomplish the same thing?** 

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2

**Additional context**:

**Comment by lane55** [comment]
Analysis: what judgement/response should pc2 give for the limit exceeded?

**Comment by lane55** [comment]
Add Next Contest to provide a way like DOMJudge to limit compile time.

**Comment by clevengr** [comment]
I thought we were going to use "Next Contest" to mean "this item is critical to be done before the next contest".  I don't consider this item "critical", in that (1) we have a known, easy workaround (the Primary will report "CE" but the Shadow will continue with the execution cycle, so we'll get a mismatch which is easy to understand), and (2) it happens _EXTREMELY RARELY_ (I think I've seen it maybe once in all the time we've been using a CCS that supports it.   These two factors lead me to believe this issue does not rise to the level of "critical to fix before the next contest".

**Comment by johnbrvc** [comment]
> I thought we were going to use "Next Contest" to mean "this item is critical to be done before the next contest". I don't consider this item "critical", in that (1) we have a known, easy workaround (the Primary will report "CE" but the Shadow will continue with the execution cycle, so we'll get a mismatch which is easy to understand), and (2) it happens _EXTREMELY RARELY_ (I think I've seen it maybe once in all the time we've been using a CCS that supports it. These two factors lead me to believe this issue does not rise to the level of "critical to fix before the next contest".

I believe there were 5 or 6 instances of it during the NAC Dress, and 1 during the NAC Real this year.

**Comment by clevengr** [comment]
>> I thought we were going to use "Next Contest" to mean "this item is critical to be done before the next contest". I don't consider this item "critical", in that (1) we have a known, easy workaround (the Primary will report "CE" but the Shadow will continue with the execution cycle, so we'll get a mismatch which is easy to understand), and (2) it happens EXTREMELY RARELY (I think I've seen it maybe once in all the time we've been using a CCS that supports it. These two factors lead me to believe this issue does not rise to the level of "critical to fix before the next contest".

>I believe there were 5 or 6 instances of it during the NAC Dress, and 1 during the NAC Real this year.

Ok, but doesn't that just mean the most likely scenario is that ONE team tried something at NAC 2023 that triggered this, and that in general it's an _extremely rare_ phenomenon?   How many OTHER times have you ever seen it, and all the contests you've run?

In any case, as I pointed out above, _we have a clear, simply workaround_:  the Shadow will disagree with the Primary, but in a way that's extremely easy to quickly explain.  That's why I question the relative importance of making this a "NEXT CONTEST, must finish by Sept 15th freeze" issue...

**Comment by johnbrvc** [comment]
Closing issue.  Addressed with PR #813
