### ISSUE TITLE
Provide a way to compare results (tsv) data

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#615]
**Is your feature request related to a problem?** 

One of the shadow tasks is to compare the results.tsv data

**Feature Description**: 

Add a way to compare two results.tsv files.

**Have you considered other ways to accomplish the same thing?** 

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

**Additional context**:

**Comment by clevengr** [comment]
It appears this Issue is duplicated by Issue #760 (actually, I think #760 is a super-set of this issue).  If so, this issue should be marked as a duplicate and closed, in favor of #760.

**Comment by johnbrvc** [comment]
Closed as per the above comments.
