### ISSUE TITLE
Duplicate files in team submission throws exception in web services /submissions/xx/files endpoint

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#631]
**Describe the issue**: 

If a team makes a submission in which they specify the same file multiple times (e.g. if the "main" file and one of the "Auxiliary" files are the same) it causes an exception when referencing the web services "/contest/submissions/xx/files" endpoint (which is supposed to return a ZIP file containing the files in the submission). 

The exception happens during the zipping step in the `SubmissionService` class; it occurs because a ZIP file cannot contain multiple copies of the same file.  Specifically, the exception occurs at line 265 of method `createZip()`.  

**To Reproduce**:

- Start a server with a contest containing at least one problem and one team.
- Start a team client.
- Submit a run where the same file has been added to the Submission file list more than once.
- Start an Event Feed client.
- Use the EF client "Web Services" tab to start the web server.
- Open a browser to the URL `https://localhost:50443/contest/submissions/xx/files`,  where "localhost" represents the IP address of the web server and "xx" is the number of the submission.

**Expected behavior**: 

The web service should return a zip of the files making up the submission.

**Actual behavior**:

The web service throws an exception (which can be seen in the FEEDER log), and returns "Not Found".

**Environment**:
All

**Log Info**:  

An example of the Event Feeder exception is shown below.

```
221203 121537.013|INFO|qtp294235476-45|log|Got a reply from the server...
221203 121537.013|INFO|qtp294235476-45|log|Returning runFiles: ["MainFile":"hello.java","OtherFiles":["name":"hello.java","name":"hello.java"]]
221203 121537.023|FINER|qtp294235476-45|getSubmissionFiles|THROW
|java.util.zip.ZipException: duplicate entry: hello.java
|    at java.util.zip.ZipOutputStream.putNextEntry (ZipOutputStream.java:232)
|    at edu.csus.ecs.pc2.services.web.SubmissionService.createZip (SubmissionService.java:265)
|    at edu.csus.ecs.pc2.services.web.SubmissionService.getSubmissionFiles (SubmissionService.java:215)
|    at sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
|    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
```

**Screenshots**: 

The following shows an example of a team submitting a Run with duplicate file names, which will cause the above exception in the web services `/contest/submissions/xx/files` endpoint.  (The example shows the same file submitted THREE times, but all it takes is TWO occurences of the same file to generate the exception.)

![image](https://user-images.githubusercontent.com/9256691/205462076-4467b19a-17c6-4833-89dc-617db60eb3db.png)

**Comment by lane55** [comment]
The question is where to fix this problem.

**Comment by clevengr** [comment]
> The question is where to fix this problem. 1 - do not allow the team to submit identical files or 2 - on create of the zip only add one file? Note that in the zip file it adds the basename for the file so if a submission is from a/Hello.java and d/Hello.java - which one would be picked?

After discussing it here we're opting for the latter -- suppress adding duplicates in the zipping.  We can of course revise this later, but that's what I've implemented and will shortly push.

Regarding the basename issue (team submits same file from two different directories), the check file2.equals(file2) will compare the absolute path (not just the basename), so a/hello.java will be a different file from b/hello.java.

**Comment by lane55** [comment]
This only is a fix for the team GUI not WTI, so when WTI allows multiple files that will need to be fixed too.
