### ISSUE TITLE
Automate copying of non-xsl files into target scoreboard directories 

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#688]
**Is your feature request related to a problem?** 

Yes.  When the scoreboard generates the html there are
needed files .css and .png files.  Those files must
be manually copied.

**Feature Description**: 

For all non .xsl files in the data/xml copy those files into
the html and public_html directories, same directories as
the directories where the html files are created.

**Have you considered other ways to accomplish the same thing?** 

Manually done.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Each time the html is generated, copy the non xsl files.

Consider not copying the files if the files are identical.
For exmaple
02/04/2023  07:42 PM             2,070 standings.css

if the file in xsl is a differnt time or size, then update the standings.css
02/04/2023  07:55 PM             2,555 standings.css

**Additional context**:

**Comment by lane55** [comment]
Also copy standings.css into data/xml

**Comment by troy2914** [comment]
none of the current xsl rely on an external css.   Should we still copy it?
