### ISSUE TITLE
Scoreboard/DSA shows wrong frozen time 

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#692]
**Describe the issue**: 

Board shows incorrect freeze time

In this ttest case it shows 

Scoreboard will be frozen with 43200 hours ...
when should show
Scoreboard will be frozen with 12 hours ...

Work around is to put 0 in front of freeze time, thus:
scoreboard-freeze-length: 012:00:00 

**To Reproduce**: 

Put this into yaml
scoreboard-freeze-length: 12:00:00 shows 

**Expected behavior**: 

Scoreboard should show:
Scoreboard will be frozen with 12 hours ...

**Actual behavior**: 

Scoreboard shows:
Scoreboard will be frozen with 43200 hours ...

**Environment**: 

All.

**Log Info**:  

**Screenshots**:  

**Additional context**:

**Comment by troy2914** [comment]
tested with the current release, it shows
Scoreboard will be frozen with 12 hours remaining in the contest; all submissions after that will be shown as 'Pending'

I believe this was fixed with #67  so dump of #67
