### ISSUE TITLE
Change default to not load sample test data sets (disable feature #244)

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#700]
**Describe the issue**: 

Temporarily disable #244, there is a bug, the fix for that bug is described in #701 

This change defaults to not load samples data files as coded in #244

Work around:
in contest.yaml use this
load-sample-judges-data: false

Code fix to change default to FALSE
in class ContestSnakeYAMLLoader change
 boolean loadSamples = fetchBooleanValue(content, LOAD_SAMPLE_JUDGES_DATA, true);
to 
boolean loadSamples = fetchBooleanValue(content, LOAD_SAMPLE_JUDGES_DATA, **false**);

**To Reproduce**: please describe, in order, the steps to reproduce the behavior:

**Expected behavior**: please provide a description of what you *expected* to happen when you took the above steps:  

**Actual behavior**: please describe what _actually_ happened when you took the above steps:

**Environment**: please complete the following information:
 - OS name and version under which the issue was detected (e.g. Windows 10 or Ubuntu 18.04):
 - PC2 Version (e.g. 9.7.0):   
 - Browser (if the bug is related to web-based team clients) (e.g. _Chrome Version 75.0.3770.142_ or _Safari Version 11.1.2_):

**Log Info**:  PC^2 generates logs (in the **logs** folder for client modules; under the **profiles** folder for the PC2 Server).  Please review the relevant logs and provide copies of them as attachments -- particularly if the logs show Exceptions being thrown.  

**Screenshots**:  if applicable, please add attachments showing screenshots to help explain the issue.

**Additional context**: please add any other context about the issue here.

**Comment by clevengr** [comment]
Just to be clear, this update to #244 should be considered temporary; when #701 is implemented this change should be reverted so that the default IS to load both samples and secret data files.

**Comment by troy2914** [comment]
#703 was merged,  closing this ticket.
