### ISSUE TITLE
Irregularly formatted scoreboard freeze time causes resolver to fail

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#716]
**Describe the issue**:
In `contest.yaml`, if a score-board-free-length of 0:60:00 is specified (60 minutes), this causes an error when the event feed is read by the resolver (throws an exception in the resolver).  May be related to #67 

**To Reproduce**: 
Hard, time consuming method:
Create a new contest where the score-board-freeze-length is 0:60:00, or using the administrator settings, set the freeze
time to be 0:60:00, or 0:69:00 for example.
Run the contest.
Produce an event feed.
Try to load the event feed into the resolver.
Resolver will get an exception due to the fact that "60" is an invalid value or the 'minutes' field.  It is expecting 1:00:00 instead.

Easy, hack method:
Edit an existing, completed `event-feed.json` file, and modify the `"type":"contest"` record at the beginning to have a `scoreboard_freeze_duration `of "0:60:00" for example.  ex:
`{"type":"contest","id":"Default-9116245442745986685","data":{"id":"Default-9116245442745986685","name":"real2022","formal_name":"ICPC Greater NY Regional Contest","start_time":"2023-02-26T11:04:42.450-05:00","duration":"5:00:00.000","scoreboard_freeze_duration":"1:09:00","penalty_time":20},"token":"cdV0"}`
Try to load the modified json into the resolver.
Resolver will get an exception due to the fact that "60" is an invalid value for the 'minutes' field.  It is expecting 1:00:00 instead.

**Expected behavior**: 
Hard to say what is expected.  I know what I expect, but it's really what the resolver expects.   Is 0:60:00 legal?  I don't see why not.  But then is, 0:69:00 legal? (meaning 1:09:00).  Sure, it should be I would think.
I would expect it to accept the value, but alas, it does not.

**Actual behavior**:
Resolver generates and exception and won't resolve the contest since there is no freeze time.

**Environment**: 
All.

**Log Info**:

**Screenshots**:

**Additional context**:
Perhaps pc2 should normalize the freeze time before it spits it out on the event feed.  eg.  0:69:00 -> 1:09:00.

**Comment by troy2914** [comment]
I don't think 0:60:00 is a valid format for ISO 8601 extended time format.

<h2><span class="mw-headline" id="Times">Times</span></h2>

Thh:mm:ss.sss | or | Thhmmss.sss
-- | -- | --
Thh:mm:ss | or | Thhmmss
Thh:mm | or | Thhmm
Thh |   |  


<p>ISO 8601 uses the <a href="https://en.wikipedia.org/wiki/24-hour_clock" title="24-hour clock">24-hour clock</a> system. As of ISO 8601-1:2019, the <i>basic format</i> is T[hh][mm][ss] and the <i>extended format</i> is T[hh]:[mm]:[ss]. Earlier versions omitted the T (representing time) in both formats.
</p>
<ul><li>[hh] refers to a zero-padded <a href="https://en.wikipedia.org/wiki/Hour" title="Hour">hour</a> between 00 and 24.</li>
<li>[mm] refers to a zero-padded <a href="https://en.wikipedia.org/wiki/Minute" title="Minute">minute</a> between 00 and 59.</li>
<li>[ss] refers to a zero-padded <a href="https://en.wikipedia.org/wiki/Second" title="Second">second</a> between 00 and 60 (where 60 is only used to denote an added <a href="https://en.wikipedia.org/wiki/Leap_second" title="Leap second">leap second</a>).</li></ul>Times
Thh:mm:ss.sss 	or 	Thhmmss.sss
Thh:mm:ss 	or 	Thhmmss
Thh:mm 	or 	Thhmm
Thh 		

ISO 8601 uses the [24-hour clock](https://en.wikipedia.org/wiki/24-hour_clock) system. As of ISO 8601-1:2019, the basic format is T[hh][mm][ss] and the extended format is T[hh]:[mm]:[ss]. Earlier versions omitted the T (representing time) in both formats.

    [hh] refers to a zero-padded [hour](https://en.wikipedia.org/wiki/Hour) between 00 and 24.
    [mm] refers to a zero-padded [minute](https://en.wikipedia.org/wiki/Minute) between 00 and 59.
    [ss] refers to a zero-padded [second](https://en.wikipedia.org/wiki/Second) between 00 and 60 (where 60 is only used to denote an added [leap second](https://en.wikipedia.org/wiki/Leap_second)).

**Comment by johnbrvc** [comment]
Fixed with PR #744
