### ISSUE TITLE
Add CLICS version endpoint as root endpoint and api

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#725]
**Is your feature request related to a problem?** 

Non-compliance with CLICS API Spec.

**Feature Description**: 

Implement a version end point.
Create a "empty" return value, empty JSON array.

See spec at https://ccs-specs.icpc.io/2022-07/contest_api#api-information

Can test using 
```
curl -u admin:admin --insecure https://localhost:50443/
```

**Have you considered other ways to accomplish the same thing?** 

There are none.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add endpoint /version end point based on VersionInfo
Add public IVersionInfo getVersionInfo() to IContest to provide version info to WTI.

**Additional context**:

**Comment by troy2914** [comment]
This should have been closed with #726
