### ISSUE TITLE
Add sample data/testing data, improve/add unit tests.

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#749]
**Is your feature request related to a problem?** 

No.  These are CI changes used improve unit tests,
add sample data files and other changes that have no impact
on pc2 source code.

The intent is to create a number of small PRs to improve
the unit tests and sample data.

**Feature Description**: 

Add/improve unit tests.
Add sample data files.

**Have you considered other ways to accomplish the same thing?** 

No other way.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

No. 

**Additional context**:

**Comment by troy2914** [comment]
#750 was merged, closing this.
