### ISSUE TITLE
Add a feature to compare results files, export files, produce a results comprison report

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#760]
**Is your feature request related to a problem?** 

Yes, the EOC steps to compare the CCC results file pc2
export and compare files is not automated.

**Feature Description**: 

Ultimately create two tasks/output
1.  an export results file feature
2.  a report to compare the pc2 results with another CCS results files.
   2a.  input would be the other CCS results dir, ex nac23real/results/domjudge.

Optional is to compare existing results file by providing two
results dir, ex results/pc2 results/domjudge

Current results files to compare, from EOC doc
  https://docs.google.com/document/d/1uwAagoskpQ8TGqqt3yDsGXcwEZbCsvg5yYOcG_hwnRQ/edit#
are:
results.tsv
(results.csv file if/when available #351)
scoreboard.json
awards.json

**Have you considered other ways to accomplish the same thing?** 

Very manual, some script solutions.

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add a new Report to export the files listed above.

On the Finalize tab add feature to compare the pc2 results snd domjudge results.

**Additional context**:

**Comment by lane55** [comment]
Design requirements
Provide a new Pane that has
title and text field for output drectoy for results reports/files, add button with open dialog to pick dir
title and text field for other directory, primary results file, , add button with open dialog to pick dir
Add button to produce results compare report
Add What's this icon/component for the two text fields.

**Comment by lane55** [comment]
For both text fields, save any changes local to user (add items to ClientSettings)

**Comment by clevengr** [comment]
It appears that this issue, and the corresponding PR work being done on it, duplicates (actually, is a super-set of) Issue #592.  If so, #592 should probably be marked as a duplicate, and closed in favor of this issue.

**Comment by clevengr** [comment]
It appears that this issue, and the corresponding PR work being done on it, duplicates (actually, is a super-set of) Issue #615. If so, #615 should probably be marked as a duplicate, and closed in favor of this issue.
