### ISSUE TITLE
Accept CLICS spec compliant contest.yaml file

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#784]
**Is your feature request related to a problem?**
Currently, an undocumented `contest.yaml` format is the only format accepted by PC2 - this is a problem.  Other parts of PC2 are, in fact aware of the CLICS spec `contest.json `(`CLICSContests.json`).  It therefore makes sense that PC2 should check if a CLICS compliant `contest.yaml` is being loaded, and, if so, accept it.  The draft spec, (soon to be 2023-06), should be used, although the _contest_ API/record format has not changed much in any of the published CLICS specs.  Since the 2022-07 spec is essentially the same for the purposes of this feature, that can be used and is found [here](https://ccs-specs.icpc.io/2022-07/contest_api#contests).
...

**Feature Description**: 
Add support for CLICS compliant `contests.yam`l.

In order to be compliant, the following properties are **required**:

- `id` (what PC2 calls `short-name`)
- `name `(sort of what PC2 calls `name`)
- `duration `(what PC2 calls `duration`)
- `scoreboard_type` (required: `pass-fail` for PC2)
- `penalty_time` (required, but alas, not used by PC2 as suggested in Issue #785)

In addition, other (optional) properties that PC2 uses have new names that must be used if the `contest.yaml` needs them:

- `start_time` (PC2 calls this `start-time`)
- `scoreboard_freeze_duration `(PC2 calls this by a couple of different names)

...

**Have you considered other ways to accomplish the same thing?** 
Manually edit a compliant `contests.yaml` file to match what PC2 is looking for.
...

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?** 
Change the Snake loader logic to see if the` contests.yaml `is CLICS spec compliant, and if so, use those fields.
...

**Additional context**: 
**WF46/WF47** in _Sharm_ have `contest.yaml `files from Kattis/DOMjudge years past that are at least partially compliant with the CLICS spec.  It therefore makes sense for PC2 to be able to read CLICS compliant `contest.yaml` files to avoid having to manually edit them and have separate copies.
...

**Comment by lane55** [comment]
This feature request is not testable as is.
There should be a specific list of testable feature requirements.
Also referening to a spec as a reference is ok, but "make it compliant" is ok for a title,
but either requires analysis to determine which requirements need to be met to
satisify/meet what is "compliant"

**Comment by johnbrvc** [comment]
> 

I was not under the impression that _new feature_ requests must have a "_how to test_" section - perhaps that should be added to the template for _features_; I have the test procedure in the PR #786.

I assumed that "_making it compliant_" was clear.  Compliant means, well... compliant with the spec.  Adheres to the spec.  That being said, the spec is readily accessible on the [CLICS specs page here](https://ccs-specs.icpc.io/2022-07/contest_api#contests) - there's no point in duplicating the whole section.  In a nutshell, for the case of "**_Contests_**", in order to be compliant, the following properties are **required**:

- `id` (what PC2 calls `short-name`)
- `name `(what PC2 calls `name`)
- `duration `(what PC2 calls `duration`)
- `scoreboard_type` (required: `pass-fail` for PC2)
- `penalty_time` (required, but alas, not used by PC2 as suggested in Issue #785)

In addition, other (optional) properties that PC2 uses have new names that must be used if the `contest.yaml` needs them:

- `start_time` (PC2 calls this `start-time`)
- `scoreboard_freeze_duration `(PC2 calls this by a couple of different names)

So, in order to comply with the spec, PC2 must be able to parse a `contest.yaml` that uses the aforementioned properties, in addition to supporting the legacy properties for older `contest.yaml `files (that is, we can't break anything).
