### ISSUE TITLE
Per-problem output limit in problem.yaml has wrong units

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#801]
**Describe the issue**: please provide a clear and concise description of what the bug is.  
The CLICS Problem Package format specification states that the per-problem output limit property is in MiB.  PC2 interprets this property as KiB.

![image](https://github.com/pc2ccs/pc2v9/assets/5657363/f8b2be8f-27ae-4a9c-9780-2113a719ca27)

Needless to say, this could lead to errant "output limit exceeded" judgements (WA).

**To Reproduce**:
Specify a per-problem output value of 16.  Note that PC2 reports this as 16KB:

![image](https://github.com/pc2ccs/pc2v9/assets/5657363/b8b2c706-158a-4c4d-b4e5-f32eb0be7779)

**Expected behavior**: 
The value should be converted to MiB.

**Actual behavior**: 
The value is converted to KiB.

**Environment**:
All.

**Log Info**:  

**Screenshots**:  

**Additional context**: 
Observed while testing wfsharm/wf46/systest1 contest.  The ETA problem has a custom output limit.

**Comment by troy2914** [comment]
missed the fixes #801 in your commit message.  Closing.
