### ISSUE TITLE
Coding Style Guidelines Does not Exist. Hyperlink Broken

### ISSUE THREAD

**Issue by kkarakas** [pc2ccs/pc2v9#816]
**Describe the issue**: "PC^2 Coding Style Guidelines document" hyperlink found in [CONTRIBUTING.MD](https://github.com/pc2ccs/pc2v9/blob/develop/CONTRIBUTING.MD#codingstyle), specifically in "Coding Style", leads to a 404. There is also another same hyperlink that is broken found in "Pull Request Submission Guidelines"

**Expected behavior**: Should lead to that document.

**Actual behavior**: 404

**Environment**: N/A

**Comment by johnbrvc** [comment]
Yes, things were moved around awhile back.
In the meantime, until we get a chance to through and fix those links (and probably others), this page, which you probably already found, SHOULD have the required information: [PC2 Developer's Notes](https://github.com/pc2ccs/pc2v9/wiki/PC2-Developer%27s-Notes)

**Comment by clevengr** [comment]
As @johnbrvc pointed out, there is existing documentation which covers the material which was originally intended to be in the `CodingStyle` document.  In fact there is (never was) such a document. I've submitted a PR which updates the `Contributing` file to point to the appropriate places in the existing documentation.  Many thanks to @kkarakas for pointing out the bad link(s).

**Comment by kkarakas** [comment]
Great! No problem!
