### ISSUE TITLE
Standings index XSL files need to be updated for multiple groups

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#917]
> > > > also maybe the samps/web/xsl xsl should be updated like index.xsl was changed?
> > > 
> > > 
> > > actually, thinking when the groups gets committed those samps/web/xsl are unneeded?
> > 
> > 
> > Probably not.
> > The real "pc2" provided `data/xsl/index.xsl` will have to be fixed to provide links to other groups' standings pages (assuming, such other groups exist). In addition, it will have to be aware - somehow - of what group **IT** is, so it doesn't include a link to itself in the list of links. That is, we can't simply `for-each` group, generate a standings link - or it would generate a link to itself. For **_PacNW_**, it looks like we'll need a custom one as well, since you add other things to the standings page (technical notes link, sample data link), as well as don't include the "other" division's groups. A D1 page will not include all the D2 links, only a link to the "D2" page. I'm not sure how that will work. At GNY we provide a link on the desktop to the "problem set page", which has links to the problem statements (all zipped or individual pdf), as well as links to the sample data (all zipped up, or individual files) on THAT page. You guys do it a bit differently. <img alt="image" width="724" src="https://private-user-images.githubusercontent.com/5657363/298405996-7cef936c-1d59-44b2-ba51-144bb7b4a24d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzEyMjcsIm5iZiI6MTcwNTg3MDkyNywicGF0aCI6Ii81NjU3MzYzLzI5ODQwNTk5Ni03Y2VmOTM2Yy0xZDU5LTQ0YjItYmE1MS0xNDRiYjdiNGEyNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMjEwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjMjcwNTlkYTg3ZmUxMGYzYjVmOTEyNDQzZmJiZjc0MTE2YWY5YmExNDE5YTU2NTAyNDBmOGFlZWMyYzU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nek0n7pPKlCTdk9TNh03hcK7zABEoX1pjwqi_m8m5ME">
> 
> Okay, in that case, can we update the samps/web stuff to follow the changes made to the data/xsl bits.

I guess the question is, should we make this a separate issue?  These XSL changes are only relevant for "group" type standings, which is really not the scope of this issue/PR.

_Originally posted by @johnbrvc in https://github.com/pc2ccs/pc2v9/issues/915#issuecomment-1908050028_

**Comment by troy2914** [comment]
i also did general cleanup, like moving the standings.css into the xsl folder, and removing the old images that referred to ACM or IBM.
