### ISSUE TITLE
Website should support downloading tar.gz files in addition to .zip

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#93]
**Is your feature request related to a problem?** 
Yes -- the problem is that there is currently no way on the pc2ccs.github.io website to download the **tar.gz** artifacts from a build (even though every build creates the appropriate artifacts and posts them to the appropriate GitHub "build" repo).  

**Feature Description**:  
- On the "Home" page of the website, in the "downloads" section, do the following:
  -  Expand each of the three current download links to contain the file extension (for example, right now it says "Stable Release: PC² version 9.6.0-5102"; it should say "Stable Release: PC² version 9.6.0-5102.zip".
  - Add a _second_ link, on the same line but to the right of the existing link, which provides a link to download the **tar.gz** version of the file (for example, a second link like "PC² version 9.6.0-5102.tar.gz".
   - There should be a nice amount of space between the text label "Stable Release:" and the first link, and likewise space separating the two links.

- On the "Current Downloads" page, do the following:
   - add three new buttons (one blue, two red), each to the right of the corresponding existing buttons. 
   - change the label text in each of the three _existing_ buttons to indicate that the button downloads a **.zip** file.  (For example, the current existing blue button, for downloading the "latest stable release", should now read "Download stable PC&sup2; version (9.6.0-5102) in **.zip** format"; and analogous changes to the other two existing (red) buttons.)
   - Set the labels in the three _new_ buttons to have similar text, except saying "...in **.tar.gz** format".

- On the "Previous Stable Downloads" page, do the following:
   - add new links (that is, new table data entries containing links) to the right of each existing ".zip" link which links to (downloads) the corresponding **.tar.gz** file.   
   - Include the corresponding **.sha256** and **.sha512** links (in parentheses) next to the **.tar.gz** links.
   - Include links to download the **.tar.gz** files for the "API" downloads in a similar manner.
   - Since the file sizes are going to be different for the **.tar.gz** downloads, display each file size  _after_ the corresponding link, in parentheses, in front of the SHA links.  For example, a table row might now look like:

`PC2 System     pc2v9.6.0-5102.zip  (22.53 MB) (sha256, sha512)    pc2v9.6.0-51-2.tar.gz (23.02 MB) (sha256, sha512)  `
   with appropriate cell spacing between the row data items.

- On the "All Builds" page, make changes corresponding to those described above for the "Previous Stable Downloads" page (add the **.tar.gz** links, move the file sizes after the links, etc.)

**Have you considered other ways to accomplish the same thing?** 
Yes.  I'm not absolutely stuck on _exactly_  the above format, but the basic requirements are:
- all pages which support downloading a **.zip** should _also_ support downloading the corresponding **.tar.gz**.
- the tabular displays (e.g. "All Builds") should display the **.tar.gz** information on the _same row_ as currently used for the **.zip** information.

**Comment by troy2914** [comment]
<img width="1203" alt="Screen Shot 2020-05-16 at 11 41 51 AM" src="https://user-images.githubusercontent.com/8680944/82127677-4b11b280-976a-11ea-8b94-99235c2feab8.png">

Is that enough space?  I did not change the space between the colon and the first link.

**Comment by troy2914** [comment]
How about "as blah" instead of "in blah format"?   Especially when you get the delevop buttons they are getting verify long.

**Comment by troy2914** [comment]
<img width="1207" alt="Screen Shot 2020-05-16 at 11 49 25 AM" src="https://user-images.githubusercontent.com/8680944/82127813-50233180-976b-11ea-82be-5a7736221bf3.png">
Let me know you want more spacing on that.

**Comment by troy2914** [comment]
Btw, i am pretty sure the api is only available as a zip.

**Comment by clevengr** [comment]
> <img alt="Screen Shot 2020-05-16 at 11 41 51 AM" width="1203" src="https://user-images.githubusercontent.com/8680944/82127677-4b11b280-976a-11ea-8b94-99235c2feab8.png">
> 
> Is that enough space? I did not change the space between the colon and the first link.

Space between the links is fine.  It would be nice if there was (at least) that amount of space after the colon, before the first link...

**Comment by clevengr** [comment]
> How about "as blah" instead of "in blah format"? Especially when you get the delevop buttons they are getting verify long.

Yep, "as blah" looks fine.   Maybe we could shorten all the buttons by _removing the version number from them_?   The buttons all have a line right above them giving the version number; I think it would work ok to have it look like:

The latest stable release PC&sup2; version is 9.6.0-5102, released on 02 January 2019
`Download stable PC2; version as zip`         `Download stable PC2 version as tar.gz`

**Comment by clevengr** [comment]
> <img alt="Screen Shot 2020-05-16 at 11 49 25 AM" width="1207" src="https://user-images.githubusercontent.com/8680944/82127813-50233180-976b-11ea-82be-5a7736221bf3.png">
> 
> Let me know you want more spacing on that.

Yes, I think it would look better with substantially more spacing between the buttons...

**Comment by clevengr** [comment]
> > <img alt="Screen Shot 2020-05-16 at 11 49 25 AM" width="1207" src="https://user-images.githubusercontent.com/8680944/82127813-50233180-976b-11ea-82be-5a7736221bf3.png">
> > Let me know you want more spacing on that.
> 
> Yes, I think it would look better with substantially more spacing between the buttons...

It would also look better if there was space below each pair of buttons, separating them from the "title" for the next download pair...

**Comment by clevengr** [comment]
> Btw, i am pretty sure the api is only available as a zip.

Ok, if it's only currently available as a zip then lets leave it like that.  Outside the scope of this issue; if someone feels strongly that we need a tar.gz for that as well then we can file a separate, new issue.

**Comment by troy2914** [comment]
<img width="1232" alt="Screen Shot 2020-05-16 at 12 10 30 PM" src="https://user-images.githubusercontent.com/8680944/82128213-4222e000-976e-11ea-804e-96d199878c16.png">
spacing added to current

**Comment by troy2914** [comment]
<img width="1211" alt="Screen Shot 2020-05-16 at 12 13 55 PM" src="https://user-images.githubusercontent.com/8680944/82128270-c07f8200-976e-11ea-83af-958ddf43bd2f.png">
spacing added to home

**Comment by troy2914** [comment]
it seems to me that adding those .tar.gz links to the right of the existing zip links would make the row too wide,  especially on the all builds page.

**Comment by clevengr** [comment]
> <img alt="Screen Shot 2020-05-16 at 12 13 55 PM" width="1211" src="https://user-images.githubusercontent.com/8680944/82128270-c07f8200-976e-11ea-83af-958ddf43bd2f.png">
> 
> spacing added to home

Looks great.

**Comment by clevengr** [comment]
> it seems to me that adding those .tar.gz links to the right of the existing zip links would make the row too wide, especially on the all builds page.

Possibly, although maybe that could be solved by leaving the "version number" out of the links?  Or maybe a better solution is to have another table row for the tar.gz links?    (As long as the data lines up in columns I think that would be ok, especially if there was maybe an extra (blank) row separating each "inner table" from the next entry...)

**Comment by troy2914** [comment]
I am leaning towards separate row for the .tar.gz version.

**Comment by clevengr** [comment]
> I am leaning towards separate row for the .tar.gz version.

I think that should be fine, as long as the rows and columns line up...

**Comment by troy2914** [comment]
<img width="1237" alt="Screen Shot 2020-05-16 at 12 30 34 PM" src="https://user-images.githubusercontent.com/8680944/82128576-0fc6b200-9771-11ea-8729-388e8cee41b3.png">

first stab at it,  looks reasonable to me...

**Comment by troy2914** [comment]
> <img alt="Screen Shot 2020-05-16 at 12 30 34 PM" width="1237" src="https://user-images.githubusercontent.com/8680944/82128576-0fc6b200-9771-11ea-8729-388e8cee41b3.png">
> 
> first stab at it, looks reasonable to me...

well expect for the 2nd pc2.zip which links to a .tar.gz

**Comment by clevengr** [comment]
I still think it would look better if the "size" were AFTER the link (as it is, the SIZE seems to be highlighted and stands out as the "most important thing", when in fact it's mostly immaterial.
Also, since there's now TWO "PC2 System" labels, maybe they should say
"PC2 System in .zip form" ....
"PC2 System in .tar.gz form"....
It would make it easier to understand what's being offered... and it would take up some of the large horizontal empty space from the "PC2 System"  over to the links....

**Comment by troy2914** [comment]
The only issue the "in ... form" that would be appkied to the API Documentation too.

**Comment by troy2914** [comment]
well unless we did "PC2 System" then "PC2 System as tar.gz form" then "PC2 API Documentation".

**Comment by troy2914** [comment]
Also I am hesitant to move the size as that is a td in the table.

**Comment by troy2914** [comment]
<img width="1234" alt="Screen Shot 2020-05-16 at 1 18 45 PM" src="https://user-images.githubusercontent.com/8680944/82129452-cc237680-9777-11ea-88bb-9a92cd5fc58e.png">

**Comment by clevengr** [comment]
> well unless we did "PC2 System" then "PC2 System as tar.gz form" then "PC2 API Documentation".

It's not clear to me why the "PC2 System" label can't say "PC2 System in .zip form".

**Comment by troy2914** [comment]
> > well unless we did "PC2 System" then "PC2 System as tar.gz form" then "PC2 API Documentation".
> 
> It's not clear to me why the "PC2 System" label can't say "PC2 System in .zip form".

because it doesn't make sense to change "PC2 API Download" to "PC2 API Download in .zip form"

**Comment by troy2914** [comment]
> > > well unless we did "PC2 System" then "PC2 System as tar.gz form" then "PC2 API Documentation".
> > 
> > 
> > It's not clear to me why the "PC2 System" label can't say "PC2 System in .zip form".
> 
> because it doesn't make sense to change "PC2 API Download" to "PC2 API Download in .zip form"

and in case it's not clear, the same piece of code is used to generate the PC2 System and PC2 API Documentation links.

**Comment by clevengr** [comment]
> > > > well unless we did "PC2 System" then "PC2 System as tar.gz form" then "PC2 API Documentation".
> > > 
> > > 
> > > It's not clear to me why the "PC2 System" label can't say "PC2 System in .zip form".
> > 
> > 
> > because it doesn't make sense to change "PC2 API Download" to "PC2 API Download in .zip form"
> 
> and in case it's not clear, the same piece of code is used to generate the PC2 System and PC2 API Documentation links.

What piece of code is that?

**Comment by clevengr** [comment]
> Also I am hesitant to move the size as that is a td in the table.

But the link is also a td in the table, right?   What's the problem with swapping them?

**Comment by troy2914** [comment]
> > > > > well unless we did "PC2 System" then "PC2 System as tar.gz form" then "PC2 API Documentation".
> > > > 
> > > > 
> > > > It's not clear to me why the "PC2 System" label can't say "PC2 System in .zip form".
> > > 
> > > 
> > > because it doesn't make sense to change "PC2 API Download" to "PC2 API Download in .zip form"
> > 
> > 
> > and in case it's not clear, the same piece of code is used to generate the PC2 System and PC2 API Documentation links.
> 
> What piece of code is that?

website/layouts/shortcodes/previousbuilds.html

**Comment by troy2914** [comment]
> > Also I am hesitant to move the size as that is a td in the table.
> 
> But the link is also a td in the table, right? What's the problem with swapping them?

You weren't talking about swapping them, you were talking of removing that td and moving that data into the link td.

**Comment by troy2914** [comment]
<img width="1232" alt="Screen Shot 2020-05-16 at 9 03 30 PM" src="https://user-images.githubusercontent.com/8680944/82135535-b8e4cb00-97b8-11ea-8799-3e5cfa46f54c.png">

Guess it doesn't look too bad.

**Comment by troy2914** [comment]
> <img alt="Screen Shot 2020-05-16 at 9 03 30 PM" width="1232" src="https://user-images.githubusercontent.com/8680944/82135535-b8e4cb00-97b8-11ea-8799-3e5cfa46f54c.png">
> 
> Guess it doesn't look too bad.

Btw, those &sup2; are a result of that being a `hugo server` output,  vs a sed'd deployed version.
